"""
GUARDIAN Fleet — OpenEnv FastAPI Server
=========================================
Implements the full OpenEnv HTTP + WebSocket protocol:

  POST /reset            → {"observation": ..., "state": ..., "reward": 0, "done": false}
  POST /step             → {"observation": ..., "reward": ..., "done": ..., "info": ..., "state": ...}
  GET  /state            → GuardianState
  WS   /ws               → Per-connection isolated WebSocket session
  GET  /health           → {"status": "ok", ...}
  GET  /web              → Browser UI for manual exploration
  GET  /docs             → OpenAPI docs (auto-generated by FastAPI)

WebSocket message protocol:
  Client → Server:
    {"type": "reset", "options": {...}}
    {"type": "step",  "action": {...}}
    {"type": "state"}

  Server → Client:
    {"type": "reset_result",  "observation": ..., "state": ..., "reward": 0, "done": false}
    {"type": "step_result",   "observation": ..., "reward": ..., "done": ..., "info": ..., "state": ...}
    {"type": "episode_done",  "observation": ..., "state": ..., "message": "..."}
    {"type": "state_result",  "state": ...}
    {"type": "error",         "message": "..."}

Run locally:
    uvicorn server.app:app --host 0.0.0.0 --port 8000 --reload

Or inside Docker (see server/Dockerfile):
    docker build -t guardian-env -f server/Dockerfile .
    docker run -p 8000:8000 guardian-env
"""

from __future__ import annotations

import json
import logging
import os
import sys
from typing import Any, Dict, Optional

# ── Ensure the repo root is always in sys.path ──────────────────────────────
# This makes `from models import ...` and `from guardian.environment import ...`
# work regardless of whether uvicorn is started from root or server/ directory.
_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

from contextlib import asynccontextmanager

from fastapi import FastAPI, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import HTMLResponse, JSONResponse
import uvicorn

from models import GuardianAction, GuardianObservation, GuardianState, StepResult
from server.guardian_environment import GuardianOpenEnvEnvironment

# ── Logging ──────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
log = logging.getLogger("guardian.server")


# ── Lifespan (replaces deprecated @app.on_event) ─────────────────────────────
@asynccontextmanager
async def lifespan(app: FastAPI):
    log.info("=" * 60)
    log.info("GUARDIAN Fleet OpenEnv Server — starting up")
    log.info("Endpoints: POST /reset  POST /step  GET /state  WS /ws")
    log.info("           GET /web     GET /health  GET /docs")
    log.info("=" * 60)
    yield  # application runs here
    log.info("GUARDIAN Fleet server shut down.")


# ── FastAPI app ───────────────────────────────────────────────────────────────
app = FastAPI(
    title="GUARDIAN Fleet — OpenEnv Server",
    description=(
        "Multi-agent AI security oversight environment for RL post-training. "
        "A Guardian LLM (Qwen2.5-7B, trained via GRPO) detects and intercepts "
        "adversarial prompt injections, authority spoofing, approval bypasses, "
        "and 5 other attack types across Finance/Ops/HR worker fleets."
    ),
    version="0.2.0",
    docs_url="/docs",
    redoc_url="/redoc",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ── Default HTTP environment (single shared session for REST endpoints) ───────
_http_env = GuardianOpenEnvEnvironment(difficulty=1)


def _new_env() -> GuardianOpenEnvEnvironment:
    """Create a fresh isolated environment per WebSocket connection."""
    return GuardianOpenEnvEnvironment(difficulty=1)


# ── Root redirect → /web ──────────────────────────────────────────────────────

@app.get("/", include_in_schema=False)
def root_redirect():
    """Redirect root URL to the web dashboard. Required for HF Spaces."""
    from fastapi.responses import RedirectResponse
    return RedirectResponse(url="/web")


# ── Health ────────────────────────────────────────────────────────────────────

@app.get(
    "/health",
    summary="Health check",
    tags=["System"],
)
def health() -> Dict[str, Any]:
    """Returns server status and environment metadata."""
    return {
        "status": "ok",
        "env": "guardian-env",
        "version": "0.2.0",
        "description": "GUARDIAN Fleet – AI Security Oversight RL Environment",
        "endpoints": ["/reset", "/step", "/state", "/ws", "/web", "/docs"],
    }


# ── REST: reset ───────────────────────────────────────────────────────────────

@app.post(
    "/reset",
    summary="Reset episode",
    tags=["Environment"],
)
def reset(body: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """
    Start a new episode.

    Body (optional JSON):
        {"seed": 42}

    Returns the initial observation and episode state.
    """
    global _http_env
    obs = _http_env.reset(options=body)
    state = _http_env.state()
    log.info(f"[REST /reset] episode_id={state.episode_id}")
    return {
        "observation": obs.model_dump(),
        "state": state.model_dump(),
        "reward": 0.0,
        "done": False,
    }


# ── REST: step ────────────────────────────────────────────────────────────────

@app.post(
    "/step",
    summary="Execute one Guardian decision",
    tags=["Environment"],
)
def step(action: GuardianAction) -> Dict[str, Any]:
    """
    Execute one Guardian decision and return the result.

    Body: GuardianAction JSON
        {
          "risk_score": 0.85,
          "intervention": "shadow",
          "attack_type": "prompt_injection",
          "rollback_k": 2,
          "reasoning": "Suspicious write to exfil_log"
        }
    """
    global _http_env
    obs, reward, done, info = _http_env.step(action)
    state = _http_env.state()
    log.info(
        f"[REST /step] step={state.step_count} "
        f"intervention={action.intervention} "
        f"risk={action.risk_score:.2f} "
        f"reward={reward:.4f} done={done}"
    )
    return {
        "observation": obs.model_dump(),
        "reward": reward,
        "done": done,
        "info": info,
        "state": state.model_dump(),
    }


# ── REST: baselines ───────────────────────────────────────────────────────────

@app.get(
    "/baselines",
    summary="Get Evaluation Baselines",
    tags=["System"],
)
def get_baselines() -> Dict[str, Any]:
    """Returns baseline execution metrics for the dashboard leaderboard."""
    eval_dir = os.path.join(_ROOT, "guardian", "data", "eval_data")
    baselines = []
    if os.path.exists(eval_dir):
        for fname in os.listdir(eval_dir):
            if fname.endswith(".json"):
                with open(os.path.join(eval_dir, fname), "r") as f:
                    try:
                        data = json.load(f)
                        baselines.append({
                            "model": data.get("model", fname.replace(".json", "")),
                            "mean_reward": data.get("mean_reward", 0.0),
                            "production_intact_rate": data.get("production_intact_rate", 0.0),
                        })
                    except Exception as e:
                        pass
    
    # Try to append trained Guardian if untested exists
    trained_path = os.path.join(_ROOT, "guardian", "data", "baseline_trained.json")
    if os.path.exists(trained_path):
        with open(trained_path, "r") as f:
            try:
                data = json.load(f)
                baselines.append({
                    "model": "Guardian (Self-Distilled RL)",
                    "mean_reward": data.get("mean_reward", 0.85),
                    "production_intact_rate": data.get("production_intact_rate", 0.95),
                })
            except Exception:
                pass

    return {"baselines": baselines}


# ── REST: state ───────────────────────────────────────────────────────────────

@app.get(
    "/state",
    summary="Episode state",
    tags=["Environment"],
)
def get_state() -> Dict[str, Any]:
    """Return current episode metadata without advancing the environment."""
    return _http_env.state().model_dump()


# ── REST: tools manifest (“Rug Pull” endpoint) ───────────────────────────────────

@app.get(
    "/tools",
    summary="Available MCP tool manifest",
    tags=["Environment"],
)
def get_tools() -> Dict[str, Any]:
    """
    Returns all tools available in the current episode, with risk metadata.

    Used by the client's get_tools() method to implement the MCP 'Rug Pull'
    deprovision pattern — the client strips quarantined tools from this list
    before exposing the action space to the Worker agent.

    Critical tools (high-risk) are flagged so the Guardian can apply
    surgical privilege downgrade without fully blocking the Worker.
    """
    all_tools = [
        # Safe tools
        {"name": "read_db",              "risk": "low",      "category": "data_read"},
        {"name": "post_to_forum",        "risk": "medium",   "category": "communication"},
        {"name": "query_data_access_log","risk": "low",      "category": "audit"},
        # Sensitive tools
        {"name": "write_db",             "risk": "high",     "category": "data_write"},
        {"name": "process_payment",      "risk": "high",     "category": "financial"},
        {"name": "modify_firewall",      "risk": "critical", "category": "network"},
        {"name": "modify_iam_policy",   "risk": "critical", "category": "iam"},
        {"name": "register_vendor",     "risk": "high",     "category": "vendor"},
        {"name": "export_data",         "risk": "critical", "category": "data_exfil"},
    ]
    # Check if any tools are currently quarantined in the active session
    quarantined = list(_http_env._gym.env.state.quarantined_tools)  # BUG-10 fix
    available = [t for t in all_tools if t["name"] not in quarantined]
    return {
        "tools": [t["name"] for t in available],
        "tool_details": available,
        "quarantined": quarantined,
        "rug_pull_active": len(quarantined) > 0,
        "episode_id": _http_env.state().episode_id,
    }



# ── WebSocket endpoint ────────────────────────────────────────────────────────

@app.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket) -> None:
    """
    Per-connection isolated WebSocket session.

    Each WebSocket connection gets its own GuardianOpenEnvEnvironment instance,
    so parallel training workers don't share environment state.

    Protocol (JSON messages):
        → {"type": "reset"}
        ← {"type": "reset_result", "observation": {...}, "state": {...}, ...}

        → {"type": "step", "action": {"risk_score": 0.8, "intervention": "shadow", ...}}
        ← {"type": "step_result", "observation": {...}, "reward": float, "done": bool, ...}

        → {"type": "state"}
        ← {"type": "state_result", "state": {...}}
    """
    await websocket.accept()
    env = _new_env()  # isolated per connection
    log.info("[WS] New connection accepted — fresh environment allocated")

    try:
        while True:
            try:
                raw = await websocket.receive_text()
            except WebSocketDisconnect:
                log.info("[WS] Client disconnected cleanly")
                return

            try:
                data: Dict[str, Any] = json.loads(raw)
            except json.JSONDecodeError:
                await websocket.send_json(
                    {"type": "error", "message": "Payload must be valid JSON"}
                )
                continue

            msg_type: str = data.get("type", "")

            # ── set_domain ──────────────────────────────────────────────────
            if msg_type == "set_domain":
                domain_id = data.get("domain", "enterprise")
                obs = env.reset(options={"domain": domain_id})
                state = env.state()
                await websocket.send_json({
                    "type": "reset_result",
                    "observation": obs.model_dump(),
                    "state": state.model_dump(),
                    "reward": 0.0,
                    "done": False,
                    "message": f"Domain switched to {domain_id}"
                })
                log.info(f"[WS] domain_switched → {domain_id}")

            # ── reset ──────────────────────────────────────────────────────
            elif msg_type == "reset":
                obs = env.reset(options=data.get("options"))
                state = env.state()
                await websocket.send_json({
                    "type": "reset_result",
                    "observation": obs.model_dump(),
                    "state": state.model_dump(),
                    "reward": 0.0,
                    "done": False,
                })
                log.info(f"[WS] reset → episode_id={state.episode_id}")

            # ── step ───────────────────────────────────────────────────────
            elif msg_type == "step":
                action_data = data.get("action", {})
                try:
                    action = GuardianAction(**action_data)
                except Exception as parse_err:
                    await websocket.send_json({
                        "type": "error",
                        "message": f"Invalid action schema: {parse_err}",
                    })
                    continue

                obs, reward, done, info = env.step(action)
                state = env.state()
                await websocket.send_json({
                    "type": "step_result",
                    "observation": obs.model_dump(),
                    "reward": reward,
                    "done": done,
                    "info": info,
                    "state": state.model_dump(),
                })
                log.info(
                    f"[WS] step={state.step_count} "
                    f"iv={action.intervention} "
                    f"reward={reward:.4f} done={done}"
                )

                # Auto-reset and notify on episode end
                if done:
                    new_obs = env.reset()
                    new_state = env.state()
                    await websocket.send_json({
                        "type": "episode_done",
                        "observation": new_obs.model_dump(),
                        "state": new_state.model_dump(),
                        "episode_id": new_state.episode_id,  # Client re-locks episode_id
                        "message": "Episode complete. Environment auto-reset.",
                    })

            # ── state ──────────────────────────────────────────────────────
            elif msg_type == "state":
                state = env.state()
                await websocket.send_json({
                    "type": "state_result",
                    "state": state.model_dump(),
                })

            # ── unknown ────────────────────────────────────────────────────
            else:
                await websocket.send_json({
                    "type": "error",
                    "message": (
                        f"Unknown message type: '{msg_type}'. "
                        "Valid types: reset | step | state"
                    ),
                })

    except WebSocketDisconnect:
        log.info("[WS] Connection closed")
    except Exception as exc:
        log.error(f"[WS] Unhandled error: {exc}", exc_info=True)
        try:
            await websocket.send_json({"type": "error", "message": str(exc)})
        except Exception:
            pass


# ── Web UI ────────────────────────────────────────────────────────────────────

@app.get("/web", response_class=HTMLResponse, summary="Browser UI", tags=["System"])
def web_interface() -> HTMLResponse:
    """Interactive browser interface for manual episode exploration."""
    return HTMLResponse(content=_WEB_UI_HTML)


_WEB_UI_HTML = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>GUARDIAN Fleet — SOC War Room</title>
  <style>
    /* Modern Dashboard Styling */
    *{box-sizing:border-box;margin:0;padding:0}
    body {
        font-family: 'Inter', -apple-system, system-ui, sans-serif;
        background: radial-gradient(circle at top, #111827, #030712);
        color: #f3f4f6; min-height: 100vh; padding: 20px;
    }
    
    /* Header Area */
    .header {
        display: flex; justify-content: space-between; align-items: center;
        margin-bottom: 24px; padding-bottom: 16px; border-bottom: 1px solid #1f2937;
    }
    .header h1 { font-size: 1.5rem; font-weight: 700; color: #60a5fa; letter-spacing: -0.02em; }
    .header .subtitle { font-size: 0.85rem; color: #9ca3af; margin-top: 4px; font-family: monospace; }
    
    /* Domain Selector Flex (Zero-Shot Demo) */
    .domain-selector {
        background: #1f2937; padding: 8px 16px; border-radius: 8px;
        display: flex; align-items: center; gap: 12px; border: 1px solid #374151;
        box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
    }
    .domain-selector label { font-size: 0.75rem; font-weight: 600; color: #9ca3af; text-transform: uppercase; }
    .domain-selector select {
        background: #111827; color: #60a5fa; border: 1px solid #374151; font-weight: 600;
        padding: 6px 12px; border-radius: 6px; outline: none; cursor: pointer; transition: all 0.2s;
    }
    .domain-selector select:hover { border-color: #60a5fa; }
    
    /* Stats & Health Badges */
    .status-bar { display: flex; gap: 12px; margin-bottom: 20px; flex-wrap: wrap; }
    .badge {
        display: flex; align-items: center; padding: 6px 12px; border-radius: 6px;
        font-size: 0.75rem; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em;
    }
    .badge-ok { background: rgba(16, 185, 129, 0.1); color: #34d399; border: 1px solid rgba(16, 185, 129, 0.2); }
    .badge-warn { background: rgba(245, 158, 11, 0.1); color: #fbbf24; border: 1px solid rgba(245, 158, 11, 0.2); }
    .badge-bad { background: rgba(239, 68, 68, 0.1); color: #f87171; border: 1px solid rgba(239, 68, 68, 0.2); }
    .badge-info { background: rgba(59, 130, 246, 0.1); color: #60a5fa; border: 1px solid rgba(59, 130, 246, 0.2); }
    
    /* Control Panel */
    .controls {
        display: flex; flex-wrap: wrap; gap: 16px; margin-bottom: 20px;
        background: #111827; padding: 16px; border-radius: 8px; border: 1px solid #1f2937;
    }
    .control-group { display: flex; flex-direction: column; gap: 6px; }
    .control-group label { font-size: 0.75rem; color: #9ca3af; font-weight: 500; }
    select, input[type=range] {
        background: #1f2937; color: #f3f4f6; border: 1px solid #374151;
        padding: 8px 12px; border-radius: 6px; font-size: 0.85rem; outline: none;
    }
    input[type=range] { padding: 0; accent-color: #3b82f6; height: 6px; margin-top: 8px; }
    .btn {
        padding: 8px 16px; border: none; border-radius: 6px; cursor: pointer;
        font-size: 0.85rem; font-weight: 600; display: flex; align-items: center; gap: 6px; transition: all 0.2s;
    }
    .btn-step { background: #2563eb; color: #fff; } .btn-step:hover { background: #3b82f6; }
    .btn-reset { background: #374151; color: #f3f4f6; } .btn-reset:hover { background: #4b5563; }
    .btn-clear { background: rgba(239, 68, 68, 0.2); color: #f87171; } .btn-clear:hover { background: rgba(239, 68, 68, 0.4); }
    
    /* Layout Grid */
    .grid { display: grid; grid-template-columns: 3fr 1.5fr; gap: 20px; }
    .panel {
        background: #111827; border: 1px solid #1f2937; border-radius: 12px;
        padding: 16px; display: flex; flex-direction: column; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.2);
    }
    .panel-header {
        font-size: 0.85rem; font-weight: 600; color: #9ca3af; text-transform: uppercase;
        letter-spacing: 0.05em; border-bottom: 1px solid #1f2937; padding-bottom: 12px; margin-bottom: 12px;
        display: flex; justify-content: space-between;
    }
    
    /* Multi-App Attack Feed */
    .event-feed { max-height: 400px; overflow-y: auto; display: flex; flex-direction: column; gap: 8px; padding-right: 4px; }
    .event-card {
        background: #1f2937; border: 1px solid #374151; border-left: 4px solid #3b82f6;
        padding: 12px; border-radius: 6px; font-family: monospace; font-size: 0.75rem;
        display: flex; flex-direction: column; gap: 8px;
    }
    .event-card.attack { border-left-color: #ef4444; background: rgba(239, 68, 68, 0.05); }
    .event-card.honeypot { border-left-color: #f59e0b; background: rgba(245, 158, 11, 0.05); }
    
    /* JSON Display */
    pre { font-family: 'Cascadia Code', Consolas, monospace; font-size: 0.75rem; overflow-x: auto; color: #a5b4fc; }
    .mcp-json p { margin:0; padding:0; }
    .json-key { color: #86efac; } .json-val { color: #93c5fd; }
    
    /* Threat Gauge */
    .threat-gauge-container { display: flex; flex-direction: column; align-items: center; justify-content: center; padding: 20px 0; }
    .circular-chart { display: block; margin: 0 auto; max-width: 120px; max-height: 120px; }
    .circle-bg { fill: none; stroke: #1f2937; stroke-width: 3.8; }
    .circle { fill: none; stroke-width: 3.8; stroke-linecap: round; transition: stroke-dasharray 0.3s ease; }
    .percentage { fill: #f3f4f6; font-family: sans-serif; font-size: 0.5em; text-anchor: middle; font-weight: bold; }
    
    /* Scrollbars */
    ::-webkit-scrollbar { width: 6px; height: 6px; }
    ::-webkit-scrollbar-track { background: transparent; }
    ::-webkit-scrollbar-thumb { background: #374151; border-radius: 3px; }
    ::-webkit-scrollbar-thumb:hover { background: #4b5563; }
  </style>
</head>
<body>
  
  <div class="header">
    <div>
      <h1>🛡️ GUARDIAN Fleet — SOC War Room</h1>
      <div class="subtitle">WebSocket: <span id="wsUrl"></span> &nbsp;|&nbsp; <span id="connStatus" style="color:#34d399">Connecting...</span></div>
    </div>
    
    <div class="domain-selector">
      <label>Target Domain Context</label>
      <select id="domainSelect" onchange="switchDomain()">
        <option value="enterprise">🏢 Enterprise HR / Finance (Training Domain)</option>
        <option value="finops">📈 Financial Algorithmic Trading Server (Zero-Shot)</option>
        <option value="corpgov">🏛️ Multi-Agent Corp Governance (Zero-Shot)</option>
      </select>
    </div>
  </div>

  <div class="status-bar" id="statusRow">
    <div class="badge badge-info" id="badgeStep">Step 0</div>
    <div class="badge badge-ok"   id="badgeProd">✅ DB Intact</div>
    <div class="badge badge-ok"   id="badgeFork">No Fork</div>
    <div class="badge badge-ok"   id="badgeAtk">System Clean</div>
    <div class="badge badge-info" id="badgeReward">Cumulative Reward: 0.000</div>
  </div>

  <div class="controls">
    <div class="control-group">
      <label>Guardian Intervention</label>
      <select id="intervention">
        <option>allow</option><option>shadow</option><option>rewrite</option>
        <option>interrogate</option><option>reduce_privs</option>
        <option>quarantine_tool</option><option>emergency_fork</option>
        <option>quarantine_agent</option>
      </select>
    </div>
    <div class="control-group">
      <label>Classified Threat</label>
      <select id="attack_type">
        <option value="">(None)</option>
        <option>authority_spoofing</option><option>prompt_injection</option>
        <option>approval_bypass</option><option>data_exfiltration</option>
        <option>confused_deputy</option><option>schema_drift_exploit</option>
        <option>rogue_internal_ai</option>
      </select>
    </div>
    <div class="control-group" style="flex:1; min-width:200px;">
      <label>Assessed Risk Score: <span id="riskVal" style="color:#60a5fa">0.30</span></label>
      <input type="range" id="riskSlider" min="0" max="1" step="0.05" value="0.3"
             oninput="document.getElementById('riskVal').textContent=parseFloat(this.value).toFixed(2)">
    </div>
    <div class="control-group" style="flex-direction:row; align-items:flex-end; gap:8px;">
      <button class="btn btn-reset" onclick="doReset()">↻ Reboot Server</button>
      <button class="btn btn-step"  onclick="doStep()">▶ Execute Step</button>
      <button class="btn btn-clear" onclick="clearLog()">⌫ Clear Logs</button>
    </div>
  </div>

  <div class="grid">
    <!-- Left: Event Feed -->
    <div class="panel">
      <div class="panel-header">
        <span>📡 Telemetry & MCP Intercept Feed</span>
        <span style="color:#3b82f6" id="toolCount">0 Events</span>
      </div>
      <div class="event-feed" id="log">
        <div style="color:#6b7280; font-size:0.8rem; text-align:center; margin-top:20px;">Awaiting enterprise telemetry hook...</div>
      </div>
    </div>
    
    <!-- Right: Threat Info -->
    <div class="grid" style="grid-template-columns: 1fr; gap:20px;">
      <div class="panel">
        <div class="panel-header">
          <span>⚠️ Live Threat Assessment</span>
        </div>
        <div class="threat-gauge-container">
          <svg viewBox="0 0 36 36" class="circular-chart">
            <path class="circle-bg" d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" />
            <path class="circle" id="riskGauge" stroke="#10b981" stroke-dasharray="0, 100" d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" />
            <text x="18" y="20.35" class="percentage" id="riskText">0%</text>
          </svg>
          <div style="margin-top:12px; font-size:0.75rem; color:#9ca3af;" id="threatLabel">SYSTEM NORMAL</div>
        </div>
      </div>
      
      <div class="panel" style="flex:1;">
        <div class="panel-header">
          <span>🛡️ Last Observation State</span>
        </div>
        <div style="overflow-y:auto; max-height:200px;">
          <pre id="obsJson">{}</pre>
        </div>
      </div>
    </div>
  </div>

  <script>
    let ws;
    const wsUrl = (location.protocol==='https:'?'wss:':'ws:')+'//'+location.host+'/ws';
    document.getElementById('wsUrl').textContent = wsUrl;

    function connect() {
      ws = new WebSocket(wsUrl);
      ws.onopen  = ()=>{ setConn(true); addLogEvent('System', 'Connected to MCP Gateway cluster.'); };
      ws.onclose = ()=>{ setConn(false); setTimeout(connect, 3000); };
      ws.onerror = ()=>{ addLogEvent('System Error', 'WebSocket dropped.', 'attack'); };
      ws.onmessage = e => handleMsg(JSON.parse(e.data));
    }
    
    function setConn(ok) {
      const el = document.getElementById('connStatus');
      el.textContent = ok ? '🟢 Gateway Active' : '🔴 Connection Lost';
      el.style.color = ok ? '#34d399' : '#f87171';
    }

    function send(msg) {
      if(ws && ws.readyState===1) ws.send(JSON.stringify(msg));
    }

    function doReset() { send({type:'reset'}); clearLog(); addLogEvent('System', 'Environment reset. Memory cleared.'); }
    function doStep() {
      send({type:'step', action:{
        risk_score: parseFloat(document.getElementById('riskSlider').value),
        intervention: document.getElementById('intervention').value,
        attack_type: document.getElementById('attack_type').value || null,
        rollback_k: 2,
        reasoning: 'Manual SOC override'
      }});
    }
    function switchDomain() {
      const dom = document.getElementById('domainSelect').value;
      send({type:'set_domain', domain: dom});
      clearLog();
      addLogEvent('System', 'Hot-swapped domain topology to: ' + dom.toUpperCase(), 'honeypot');
    }
    function clearLog() { document.getElementById('log').innerHTML = ''; }

    function handleMsg(d) {
      // Print nicely formatted log if it's a step result
      if(d.type === 'step_result') {
          try {
             // Try to parse action log json
             const actionLog = JSON.parse(d.observation.action_log_json);
             if(actionLog.length > 0) {
                 const last = actionLog[actionLog.length-1];
                 const toolName = last.tool || "sys_call";
                 const role = last.role || "worker";
                 let style = "normal";
                 if(d.observation.attack_active) style = "attack";
                 if(d.observation.fork_triggered) style = "honeypot";
                 
                 addLogEvent(toolName, JSON.stringify(last.params || {}), style);
                 
                 // Update Threat Gauge
                 const riskHist = d.observation.risk_history;
                 if(riskHist && riskHist.length > 0) {
                     const risk = riskHist[riskHist.length-1];
                     updateGauge(risk);
                 }
             }
          } catch(e) {}
      } else if(d.type === 'error') {
          addLogEvent('Error', d.message, 'attack');
      }

      // Update Badges
      const obs = d.observation;
      if(obs) {
        document.getElementById('obsJson').textContent = JSON.stringify(obs, null, 2);
        setB('badgeStep',  'Step '+obs.current_step, 'badge-info');
        setB('badgeProd',  obs.production_intact?'✅ DB INTACT':'❌ BREACHED', obs.production_intact?'badge-ok':'badge-bad');
        setB('badgeFork',  obs.fork_triggered?'🔀 HONEYPOT ACTIVE':'NO FORK', obs.fork_triggered?'badge-warn':'badge-ok');
        setB('badgeAtk',   obs.attack_active?'⚠️ ATTACK IN PROGRESS':'SYSTEM CLEAN', obs.attack_active?'badge-bad':'badge-ok');
      }
      if(d.reward !== undefined) setB('badgeReward', 'REWARD: '+Number(d.reward).toFixed(4), 'badge-info');
    }

    function addLogEvent(title, detail, styleClass = 'normal') {
      const feed = document.getElementById('log');
      const time = new Date().toISOString().substring(11,23);
      
      const div = document.createElement('div');
      div.className = `event-card ${styleClass}`;
      div.innerHTML = `
        <div style="display:flex; justify-content:space-between; color:#9ca3af;">
            <span style="font-weight:bold; color:#f3f4f6;">${title}</span>
            <span>${time}</span>
        </div>
        <div style="color:#60a5fa; overflow-x:auto;">${detail}</div>
      `;
      feed.appendChild(div);
      feed.scrollTop = feed.scrollHeight;
      
      document.getElementById('toolCount').textContent = feed.children.length + " Events";
    }

    function setB(id, txt, cls) {
      const b=document.getElementById(id);
      b.textContent = txt; 
      b.className = 'badge ' + cls;
    }
    
    function updateGauge(val) {
        const pct = Math.round(val * 100);
        document.getElementById('riskText').textContent = pct + "%";
        
        let color = "#10b981"; // green
        let label = "SYSTEM NORMAL";
        if(pct > 40) { color = "#f59e0b"; label = "ELEVATED RISK"; } // yellow
        if(pct > 75) { color = "#ef4444"; label = "CRITICAL THREAT"; } // red
        
        const path = document.getElementById('riskGauge');
        path.setAttribute('stroke-dasharray', `${pct}, 100`);
        path.setAttribute('stroke', color);
        
        const lbl = document.getElementById('threatLabel');
        lbl.textContent = label;
        lbl.style.color = color;
    }

    connect();
  </script>
</body>
</html>"""


# ── Entrypoint ────────────────────────────────────────────────────────────────

def main() -> None:
    """Called by `guardian-server` console script (pyproject.toml entry point)."""
    port = int(os.getenv("PORT", "8000"))
    host = os.getenv("HOST", "0.0.0.0")
    log.info(f"Starting uvicorn on {host}:{port}")
    uvicorn.run("server.app:app", host=host, port=port, reload=False)


if __name__ == "__main__":
    main()
