"""
GUARDIAN Fleet — OpenEnv FastAPI Server
=========================================
Implements the full OpenEnv HTTP + WebSocket protocol:

  POST /reset            → {"observation": ..., "state": ..., "reward": 0, "done": false}
  POST /step             → {"observation": ..., "reward": ..., "done": ..., "info": ..., "state": ...}
  GET  /state            → GuardianState
  WS   /ws               → Per-connection isolated WebSocket session
  GET  /health           → {"status": "ok", ...}
  GET  /web              → Browser UI for manual exploration
  GET  /docs             → OpenAPI docs (auto-generated by FastAPI)

WebSocket message protocol:
  Client → Server:
    {"type": "reset", "options": {...}}
    {"type": "step",  "action": {...}}
    {"type": "state"}

  Server → Client:
    {"type": "reset_result",  "observation": ..., "state": ..., "reward": 0, "done": false}
    {"type": "step_result",   "observation": ..., "reward": ..., "done": ..., "info": ..., "state": ...}
    {"type": "episode_done",  "observation": ..., "state": ..., "message": "..."}
    {"type": "state_result",  "state": ...}
    {"type": "error",         "message": "..."}

Run locally:
    uvicorn server.app:app --host 0.0.0.0 --port 8000 --reload

Or inside Docker (see server/Dockerfile):
    docker build -t guardian-env -f server/Dockerfile .
    docker run -p 8000:8000 guardian-env
"""

from __future__ import annotations

import json
import logging
import os
import sys
from typing import Any, Dict, Optional

# ── Ensure the repo root is always in sys.path ──────────────────────────────
# This makes `from models import ...` and `from guardian.environment import ...`
# work regardless of whether uvicorn is started from root or server/ directory.
_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

from contextlib import asynccontextmanager

from fastapi import FastAPI, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import HTMLResponse, JSONResponse
import uvicorn

from models import GuardianAction, GuardianObservation, GuardianState, StepResult
from server.guardian_environment import GuardianOpenEnvEnvironment

try:
    from guardian.hitl.escalation import hitl_manager, get_counterfactual, AMBIGUITY_LOW, AMBIGUITY_HIGH
    _HITL_AVAILABLE = True
except ImportError:
    _HITL_AVAILABLE = False
    log = logging.getLogger("guardian.server")
    logging.getLogger("guardian.server").warning("HITL module not available — HITL endpoints disabled")

# ── Logging ──────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
log = logging.getLogger("guardian.server")


# ── Lifespan (replaces deprecated @app.on_event) ─────────────────────────────
@asynccontextmanager
async def lifespan(app: FastAPI):
    log.info("=" * 60)
    log.info("GUARDIAN Fleet OpenEnv Server — starting up")
    log.info("Endpoints: POST /reset  POST /step  GET /state  WS /ws")
    log.info("           GET /web     GET /health  GET /docs")
    log.info("=" * 60)
    yield  # application runs here
    log.info("GUARDIAN Fleet server shut down.")


# ── FastAPI app ───────────────────────────────────────────────────────────────
app = FastAPI(
    title="GUARDIAN Fleet — OpenEnv Server",
    description=(
        "Multi-agent AI security oversight environment for RL post-training. "
        "A Guardian LLM (Qwen2.5-7B, trained via GRPO) detects and intercepts "
        "adversarial prompt injections, authority spoofing, approval bypasses, "
        "and 5 other attack types across Finance/Ops/HR worker fleets."
    ),
    version="0.2.0",
    docs_url="/docs",
    redoc_url="/redoc",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ── Default HTTP environment (single shared session for REST endpoints) ───────
_http_env = GuardianOpenEnvEnvironment(difficulty=1)


def _new_env() -> GuardianOpenEnvEnvironment:
    """Create a fresh isolated environment per WebSocket connection."""
    return GuardianOpenEnvEnvironment(difficulty=1)


# ── Root redirect → /web ──────────────────────────────────────────────────────

@app.get("/", include_in_schema=False)
def root_redirect():
    """Redirect root URL to the web dashboard. Required for HF Spaces."""
    from fastapi.responses import RedirectResponse
    return RedirectResponse(url="/web")


# ── Health ────────────────────────────────────────────────────────────────────

@app.get(
    "/health",
    summary="Health check",
    tags=["System"],
)
def health() -> Dict[str, Any]:
    """Returns server status and environment metadata."""
    return {
        "status": "ok",
        "env": "guardian-env",
        "version": "0.2.0",
        "description": "GUARDIAN Fleet – AI Security Oversight RL Environment",
        "endpoints": ["/reset", "/step", "/state", "/ws", "/web", "/docs"],
    }


# ── REST: reset ───────────────────────────────────────────────────────────────

@app.post(
    "/reset",
    summary="Reset episode",
    tags=["Environment"],
)
def reset(body: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """
    Start a new episode.

    Body (optional JSON):
        {"seed": 42}

    Returns the initial observation and episode state.
    """
    global _http_env
    obs = _http_env.reset(options=body)
    state = _http_env.state()
    log.info(f"[REST /reset] episode_id={state.episode_id}")
    return {
        "observation": obs.model_dump(),
        "state": state.model_dump(),
        "reward": 0.0,
        "done": False,
    }


# ── REST: step ────────────────────────────────────────────────────────────────

@app.post(
    "/step",
    summary="Execute one Guardian decision",
    tags=["Environment"],
)
def step(action: GuardianAction) -> Dict[str, Any]:
    """
    Execute one Guardian decision and return the result.

    Body: GuardianAction JSON
        {
          "risk_score": 0.85,
          "intervention": "shadow",
          "attack_type": "prompt_injection",
          "rollback_k": 2,
          "reasoning": "Suspicious write to exfil_log"
        }
    """
    global _http_env
    obs, reward, done, info = _http_env.step(action)
    state = _http_env.state()
    log.info(
        f"[REST /step] step={state.step_count} "
        f"intervention={action.intervention} "
        f"risk={action.risk_score:.2f} "
        f"reward={reward:.4f} done={done}"
    )
    return {
        "observation": obs.model_dump(),
        "reward": reward,
        "done": done,
        "info": info,
        "state": state.model_dump(),
    }


# ── REST: baselines ───────────────────────────────────────────────────────────

@app.get(
    "/baselines",
    summary="Get Evaluation Baselines",
    tags=["System"],
)
def get_baselines() -> Dict[str, Any]:
    """Returns baseline execution metrics for the dashboard leaderboard."""
    eval_dir = os.path.join(_ROOT, "guardian", "data", "eval_data")
    baselines = []
    if os.path.exists(eval_dir):
        for fname in os.listdir(eval_dir):
            if fname.endswith(".json"):
                with open(os.path.join(eval_dir, fname), "r") as f:
                    try:
                        data = json.load(f)
                        baselines.append({
                            "model": data.get("model", fname.replace(".json", "")),
                            "mean_reward": data.get("mean_reward", 0.0),
                            "production_intact_rate": data.get("production_intact_rate", 0.0),
                        })
                    except Exception as e:
                        pass
    
    # Try to append trained Guardian if untested exists
    trained_path = os.path.join(_ROOT, "guardian", "data", "baseline_trained.json")
    if os.path.exists(trained_path):
        with open(trained_path, "r") as f:
            try:
                data = json.load(f)
                baselines.append({
                    "model": "Guardian (Self-Distilled RL)",
                    "mean_reward": data.get("mean_reward", 0.85),
                    "production_intact_rate": data.get("production_intact_rate", 0.95),
                })
            except Exception:
                pass

    return {"baselines": baselines}


# ── REST: state ───────────────────────────────────────────────────────────────

@app.get(
    "/state",
    summary="Episode state",
    tags=["Environment"],
)
def get_state() -> Dict[str, Any]:
    """Return current episode metadata without advancing the environment."""
    return _http_env.state().model_dump()


# ── REST: tools manifest (“Rug Pull” endpoint) ───────────────────────────────────

@app.get(
    "/tools",
    summary="Available MCP tool manifest",
    tags=["Environment"],
)
def get_tools() -> Dict[str, Any]:
    """
    Returns all tools available in the current episode, with risk metadata.

    Used by the client's get_tools() method to implement the MCP 'Rug Pull'
    deprovision pattern — the client strips quarantined tools from this list
    before exposing the action space to the Worker agent.

    Critical tools (high-risk) are flagged so the Guardian can apply
    surgical privilege downgrade without fully blocking the Worker.
    """
    all_tools = [
        # Safe tools
        {"name": "read_db",              "risk": "low",      "category": "data_read"},
        {"name": "post_to_forum",        "risk": "medium",   "category": "communication"},
        {"name": "query_data_access_log","risk": "low",      "category": "audit"},
        # Sensitive tools
        {"name": "write_db",             "risk": "high",     "category": "data_write"},
        {"name": "process_payment",      "risk": "high",     "category": "financial"},
        {"name": "modify_firewall",      "risk": "critical", "category": "network"},
        {"name": "modify_iam_policy",   "risk": "critical", "category": "iam"},
        {"name": "register_vendor",     "risk": "high",     "category": "vendor"},
        {"name": "export_data",         "risk": "critical", "category": "data_exfil"},
    ]
    # Check if any tools are currently quarantined in the active session
    quarantined = list(_http_env._gym.env.state.quarantined_tools)  # BUG-10 fix
    available = [t for t in all_tools if t["name"] not in quarantined]
    return {
        "tools": [t["name"] for t in available],
        "tool_details": available,
        "quarantined": quarantined,
        "rug_pull_active": len(quarantined) > 0,
        "episode_id": _http_env.state().episode_id,
    }



# ── HITL: Pending escalations ─────────────────────────────────────────────────

@app.get(
    "/hitl/pending",
    summary="List all pending HITL escalations",
    tags=["HITL"],
)
def hitl_pending() -> Dict[str, Any]:
    """
    Returns all pending human-in-the-loop escalations.
    Each entry includes the pre-formatted WhatsApp decision matrix message.
    """
    if not _HITL_AVAILABLE:
        return {"error": "HITL module not available", "pending": {}}
    return {
        "pending": hitl_manager.get_all_pending(),
        "ambiguity_zone": {"low": AMBIGUITY_LOW, "high": AMBIGUITY_HIGH},
    }


@app.post(
    "/hitl/escalate",
    summary="Create a new HITL escalation from the Web UI and fire n8n webhook",
    tags=["HITL"],
)
def hitl_escalate(body: Dict[str, Any]) -> Dict[str, Any]:
    """
    Called by the SOC War Room UI when a Gray-Zone risk is detected.
    1. Registers the escalation in the HITL manager (so resolve works later).
    2. Fires the n8n webhook to trigger the Telegram alert.
    """
    import requests as _req
    if not _HITL_AVAILABLE:
        return {"error": "HITL module not available"}

    context_id    = body.get("context_id", f"demo-{os.urandom(4).hex()}")
    tool_name     = body.get("tool_name", "unknown_tool")
    risk_score    = float(body.get("risk_score", 0.65))
    domain        = body.get("domain", "enterprise")
    classified    = body.get("classified_attack", "ambiguous_behavior")
    cap_tags      = body.get("capability_tags", "")
    counterfactual = body.get("counterfactual", "")
    tool_args     = body.get("tool_arguments", {})

    # Register full escalation in the manager so /hitl/decision can resolve it
    ctx = hitl_manager.create_escalation(
        tool_name=tool_name,
        tool_arguments=tool_args,
        risk_score=risk_score,
        classified_attack=classified,
        capability_tags=cap_tags,
        counterfactual=counterfactual,
        domain=domain,
        episode_id=body.get("episode_id", "demo"),
    )
    # The manager auto-generates the context_id; read it back
    real_ctx_id = ctx.context_id

    payload = {
        "context_id": real_ctx_id,
        "tool_name": tool_name,
        "risk_score": risk_score,
        "domain": domain,
        "classified_attack": classified,
        "capability_tags": cap_tags,
        "counterfactual": counterfactual,
    }
    try:
        _req.post(
            "http://localhost:5678/webhook-test/guardian-alert",
            json=payload,
            timeout=2,
        )
        log.info("[HITL] n8n webhook triggered for context_id=%s", real_ctx_id)
    except Exception as e:
        log.warning("[HITL] n8n webhook ping failed: %s", e)

    return {"ok": True, "context_id": real_ctx_id}


@app.post(
    "/hitl/decision",
    summary="Submit human HITL decision",
    tags=["HITL"],
)
def hitl_decision(body: Dict[str, Any]) -> Dict[str, Any]:
    """
    Submit a human decision for a pending HITL escalation.

    Body:
        {"context_id": "abc123", "decision": "allow" | "block" | "shadow"}

    Also supports plain text format from Telegram:
        {"text": "block abc123"}   ← user typed it instead of tapping button

    The decision is ALWAYS written to hitl_replay.jsonl regardless of whether
    the context_id is still in memory. This closes the self-improvement loop
    even after server restarts.
    """
    if not _HITL_AVAILABLE:
        return {"error": "HITL module not available"}

    # ── Support typed text commands ("block abc123" / "allow" / "shadow abc123")
    raw_text = body.get("text", "").strip().lower()
    if raw_text:
        parts = raw_text.split()
        if parts[0] in ("allow", "block", "shadow"):
            body["decision"] = parts[0]
            if len(parts) > 1:
                body["context_id"] = parts[1]

    context_id = body.get("context_id", f"manual-{os.urandom(3).hex()}")
    decision   = body.get("decision", "")

    if decision not in ("allow", "block", "shadow"):
        return {"error": f"Invalid decision '{decision}'. Must be: allow | block | shadow"}

    # ── Try to resolve from in-memory pending queue first
    ctx = hitl_manager.resolve_escalation(context_id, decision)  # type: ignore

    if ctx is None:
        # Context not in memory (server restarted, or manual submission)
        # Write a headless entry directly to the replay buffer — loop stays closed
        log.warning(
            "[HITL] context_id '%s' not in memory — writing headless replay entry", context_id
        )
        import datetime, json as _json
        replay_path = hitl_manager._replay_path
        os.makedirs(os.path.dirname(replay_path), exist_ok=True)
        headless_entry = {
            "context_id":             context_id,
            "timestamp":              datetime.datetime.utcnow().isoformat(),
            "tool_name":              body.get("tool_name", "unknown"),
            "classified_attack":      body.get("classified_attack", "unknown"),
            "risk_score":             body.get("risk_score", 0.65),
            "domain":                 body.get("domain", "enterprise"),
            "ground_truth_decision":  decision,
            "training_label":         f"intervention:{decision}",
            "source":                 "headless_manual",
        }
        try:
            with open(replay_path, "a", encoding="utf-8") as f:
                f.write(_json.dumps(headless_entry) + "\n")
            log.info("[HITL] 📝 Headless replay entry written for context_id=%s", context_id)
        except OSError as e:
            log.error("[HITL] Failed to write headless replay: %s", e)
            return {"error": f"Replay write failed: {e}"}

        stats = hitl_manager.get_replay_buffer_stats()
        return {
            "resolved":            True,
            "context_id":          context_id,
            "decision":            decision,
            "source":              "headless_manual",
            "replay_buffer_total": stats["total_entries"],
            "message":             (
                f"Decision '{decision}' written to replay buffer (headless). "
                f"Buffer now has {stats['total_entries']} ground-truth entries."
            ),
        }

    # ── Normal path: context was in memory, fully resolved
    stats = hitl_manager.get_replay_buffer_stats()
    log.info(
        "[HITL] Human decision: context_id=%s decision=%s replay_total=%d",
        context_id, decision, stats["total_entries"]
    )
    return {
        "resolved":            True,
        "context_id":          context_id,
        "decision":            decision,
        "tool_name":           ctx.tool_name,
        "replay_buffer_total": stats["total_entries"],
        "message":             (
            f"Decision '{decision}' logged. "
            f"Replay buffer now has {stats['total_entries']} ground-truth entries "
            f"for next GRPO training run."
        ),
    }



@app.get(
    "/hitl/replay_stats",
    summary="HITL replay buffer statistics",
    tags=["HITL"],
)
def hitl_replay_stats() -> Dict[str, Any]:
    """
    Returns statistics about the HITL replay buffer.
    Shows how many human decisions have been logged for the next GRPO training run.
    """
    if not _HITL_AVAILABLE:
        return {"error": "HITL module not available"}
    return hitl_manager.get_replay_buffer_stats()


@app.post(
    "/hitl/backtrack",
    summary="Root-cause backtrack analysis for a BLOCK decision",
    tags=["HITL"],
)
def hitl_backtrack(body: Dict[str, Any]) -> Dict[str, Any]:
    """
    Produces a full causal chain trace for a BLOCK decision.

    Traces backward from the blocked action to:
      - The first anomaly step (when risk deviated from baseline)
      - The likely injection point (where malicious instruction entered)
      - The full step-by-step causal chain
      - A plain-English incident narrative
      - Recommended post-incident actions

    Body:
        {
            "context_id": "abc123",
            "blocked_tool": "override_margin_limits",
            "blocked_at_step": 8,
            "risk_score": 0.82,
            "capability_tags": "[STATE_MOD=True|PRIV_ESC=True|FINANCIAL=Critical]",
            "attack_pattern": "confused_deputy",
            "counterfactual": "Margin reqs zeroed...",
            "domain": "finops",
            "risk_history": [0.1, 0.12, 0.15, 0.35, 0.60, 0.75, 0.80, 0.82],
            "intercept_log": [...]
        }
    """
    if not _HITL_AVAILABLE:
        return {"error": "HITL module not available"}

    try:
        from guardian.hitl.backtrack import backtrack_engine
    except ImportError:
        return {"error": "Backtrack engine not available"}

    report = backtrack_engine.analyze(
        context_id=body.get("context_id", "manual"),
        blocked_tool=body.get("blocked_tool", "unknown"),
        blocked_at_step=body.get("blocked_at_step", 0),
        risk_score=body.get("risk_score", 0.0),
        capability_tags=body.get("capability_tags", ""),
        attack_pattern=body.get("attack_pattern", "unknown"),
        counterfactual=body.get("counterfactual", ""),
        domain=body.get("domain", "enterprise"),
        intercept_log=body.get("intercept_log", []),
        risk_history=body.get("risk_history", []),
    )
    return report.to_dict()


# ── WebSocket endpoint ────────────────────────────────────────────────────────

@app.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket) -> None:
    """
    Per-connection isolated WebSocket session.

    Each WebSocket connection gets its own GuardianOpenEnvEnvironment instance,
    so parallel training workers don't share environment state.

    Protocol (JSON messages):
        → {"type": "reset"}
        ← {"type": "reset_result", "observation": {...}, "state": {...}, ...}

        → {"type": "step", "action": {"risk_score": 0.8, "intervention": "shadow", ...}}
        ← {"type": "step_result", "observation": {...}, "reward": float, "done": bool, ...}

        → {"type": "state"}
        ← {"type": "state_result", "state": {...}}
    """
    await websocket.accept()
    env = _new_env()  # isolated per connection
    log.info("[WS] New connection accepted — fresh environment allocated")

    try:
        while True:
            try:
                raw = await websocket.receive_text()
            except WebSocketDisconnect:
                log.info("[WS] Client disconnected cleanly")
                return

            try:
                data: Dict[str, Any] = json.loads(raw)
            except json.JSONDecodeError:
                await websocket.send_json(
                    {"type": "error", "message": "Payload must be valid JSON"}
                )
                continue

            msg_type: str = data.get("type", "")

            # ── set_domain ──────────────────────────────────────────────────
            if msg_type == "set_domain":
                domain_id = data.get("domain", "enterprise")
                obs = env.reset(options={"domain": domain_id})
                state = env.state()
                await websocket.send_json({
                    "type": "reset_result",
                    "observation": obs.model_dump(),
                    "state": state.model_dump(),
                    "reward": 0.0,
                    "done": False,
                    "message": f"Domain switched to {domain_id}"
                })
                log.info(f"[WS] domain_switched → {domain_id}")

            # ── reset ──────────────────────────────────────────────────────
            elif msg_type == "reset":
                obs = env.reset(options=data.get("options"))
                state = env.state()
                await websocket.send_json({
                    "type": "reset_result",
                    "observation": obs.model_dump(),
                    "state": state.model_dump(),
                    "reward": 0.0,
                    "done": False,
                })
                log.info(f"[WS] reset → episode_id={state.episode_id}")

            # ── step ───────────────────────────────────────────────────────
            elif msg_type == "step":
                action_data = data.get("action", {})
                try:
                    action = GuardianAction(**action_data)
                except Exception as parse_err:
                    await websocket.send_json({
                        "type": "error",
                        "message": f"Invalid action schema: {parse_err}",
                    })
                    continue

                obs, reward, done, info = env.step(action)
                state = env.state()
                await websocket.send_json({
                    "type": "step_result",
                    "observation": obs.model_dump(),
                    "reward": reward,
                    "done": done,
                    "info": info,
                    "state": state.model_dump(),
                })
                log.info(
                    f"[WS] step={state.step_count} "
                    f"iv={action.intervention} "
                    f"reward={reward:.4f} done={done}"
                )

                # Auto-reset and notify on episode end
                if done:
                    new_obs = env.reset()
                    new_state = env.state()
                    await websocket.send_json({
                        "type": "episode_done",
                        "observation": new_obs.model_dump(),
                        "state": new_state.model_dump(),
                        "episode_id": new_state.episode_id,  # Client re-locks episode_id
                        "message": "Episode complete. Environment auto-reset.",
                    })

            # ── state ──────────────────────────────────────────────────────
            elif msg_type == "state":
                state = env.state()
                await websocket.send_json({
                    "type": "state_result",
                    "state": state.model_dump(),
                })

            # ── unknown ────────────────────────────────────────────────────
            else:
                await websocket.send_json({
                    "type": "error",
                    "message": (
                        f"Unknown message type: '{msg_type}'. "
                        "Valid types: reset | step | state"
                    ),
                })

    except WebSocketDisconnect:
        log.info("[WS] Connection closed")
    except Exception as exc:
        log.error(f"[WS] Unhandled error: {exc}", exc_info=True)
        try:
            await websocket.send_json({"type": "error", "message": str(exc)})
        except Exception:
            pass


# ── Web UI ────────────────────────────────────────────────────────────────────

@app.get("/web", response_class=HTMLResponse, summary="Browser UI", tags=["System"])
def web_interface() -> HTMLResponse:
    """Interactive browser interface for manual episode exploration."""
    return HTMLResponse(content=_WEB_UI_HTML)


_WEB_UI_HTML = r"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>GUARDIAN — AI Security Oversight | OpenEnv</title>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&family=JetBrains+Mono:wght@400;600&display=swap" rel="stylesheet">
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

    :root {
      --bg:        #030712;
      --surface:   #0d1526;
      --surface2:  #111827;
      --border:    #1e2d45;
      --blue:      #3b82f6;
      --blue-glow: rgba(59,130,246,0.15);
      --cyan:      #22d3ee;
      --green:     #10b981;
      --amber:     #f59e0b;
      --red:       #ef4444;
      --purple:    #8b5cf6;
      --text:      #f1f5f9;
      --muted:     #64748b;
      --mono:      'JetBrains Mono', monospace;
    }

    html { scroll-behavior: smooth; }
    body { font-family: 'Inter', sans-serif; background: var(--bg); color: var(--text); min-height: 100vh; overflow-x: hidden; }

    /* ── ORBS ── */
    .orb { position: fixed; border-radius: 50%; filter: blur(120px); opacity: 0.18; pointer-events: none; z-index: 0; animation: drift 12s ease-in-out infinite; }
    .orb-1 { width: 600px; height: 600px; background: var(--blue);   top: -200px; left: -100px; animation-delay: 0s; }
    .orb-2 { width: 400px; height: 400px; background: var(--purple); bottom: 0;   right: -100px; animation-delay: 4s; }
    .orb-3 { width: 300px; height: 300px; background: var(--cyan);   top: 40%;   left: 50%;  animation-delay: 8s; }
    @keyframes drift { 0%,100%{transform:translate(0,0)} 50%{transform:translate(30px,20px)} }

    /* ── NAV ── */
    nav { position: sticky; top: 0; z-index: 100; backdrop-filter: blur(20px); background: rgba(3,7,18,0.7); border-bottom: 1px solid var(--border); padding: 0 40px; display: flex; align-items: center; justify-content: space-between; height: 60px; }
    .nav-logo { display: flex; align-items: center; gap: 10px; font-weight: 700; font-size: 1rem; color: var(--text); }
    .nav-logo .shield { width: 28px; height: 28px; background: linear-gradient(135deg, var(--blue), var(--cyan)); border-radius: 7px; display: flex; align-items: center; justify-content: center; font-size: 14px; }
    .nav-pill { font-size: 0.7rem; font-weight: 700; padding: 3px 9px; border-radius: 20px; background: rgba(59,130,246,0.12); color: var(--blue); border: 1px solid rgba(59,130,246,0.25); letter-spacing: 0.05em; }
    .nav-links { display: flex; gap: 6px; }
    .nav-links a { padding: 6px 14px; border-radius: 7px; font-size: 0.82rem; font-weight: 500; color: var(--muted); text-decoration: none; transition: all 0.2s; }
    .nav-links a:hover { background: var(--surface); color: var(--text); }
    .nav-links a.active { background: var(--blue-glow); color: var(--blue); }
    .pulse-dot { width: 7px; height: 7px; border-radius: 50%; background: var(--green); box-shadow: 0 0 8px var(--green); animation: pulse 2s infinite; display: inline-block; margin-right: 6px; }
    @keyframes pulse { 0%,100%{opacity:1;transform:scale(1)} 50%{opacity:0.5;transform:scale(1.4)} }

    /* ── HERO ── */
    .hero { position: relative; z-index: 1; padding: 90px 40px 70px; max-width: 1200px; margin: 0 auto; }
    .hero-tag { display: inline-flex; align-items: center; gap: 8px; padding: 5px 14px; border-radius: 100px; border: 1px solid var(--border); background: var(--surface); font-size: 0.75rem; color: var(--muted); font-family: var(--mono); margin-bottom: 28px; }
    .hero h1 { font-size: clamp(2.2rem, 5vw, 3.8rem); font-weight: 800; line-height: 1.1; letter-spacing: -0.03em; margin-bottom: 22px; }
    .hero h1 .grad { background: linear-gradient(135deg, #60a5fa 0%, #22d3ee 50%, #a78bfa 100%); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text; }
    .hero-sub { font-size: 1.1rem; color: var(--muted); line-height: 1.7; max-width: 640px; margin-bottom: 40px; }
    .hero-cta { display: flex; gap: 12px; flex-wrap: wrap; }
    .btn { padding: 12px 24px; border-radius: 10px; font-weight: 600; font-size: 0.9rem; cursor: pointer; transition: all 0.2s; border: none; font-family: 'Inter', sans-serif; }
    .btn-primary { background: var(--blue); color: white; box-shadow: 0 4px 20px rgba(59,130,246,0.3); }
    .btn-primary:hover { transform: translateY(-2px); box-shadow: 0 8px 30px rgba(59,130,246,0.4); }
    .btn-ghost { background: transparent; color: var(--muted); border: 1px solid var(--border); }
    .btn-ghost:hover { background: var(--surface); color: var(--text); }

    /* ── STATS ROW ── */
    .stats-row { display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; max-width:1200px; margin: 0 auto 60px; padding: 0 40px; position: relative; z-index: 1; }
    .stat-card { background: var(--surface); border: 1px solid var(--border); border-radius: 14px; padding: 22px; transition: border-color 0.2s; }
    .stat-card:hover { border-color: var(--blue); }
    .stat-num { font-size: 2rem; font-weight: 800; letter-spacing: -0.03em; }
    .stat-label { font-size: 0.78rem; color: var(--muted); margin-top: 4px; }
    .stat-blue   { color: var(--blue); }
    .stat-green  { color: var(--green); }
    .stat-amber  { color: var(--amber); }
    .stat-purple { color: var(--purple); }

    /* ── PILLARS ── */
    .section { max-width: 1200px; margin: 0 auto 60px; padding: 0 40px; position: relative; z-index: 1; }
    .section-label { font-size: 0.7rem; font-weight: 700; letter-spacing: 0.12em; text-transform: uppercase; color: var(--blue); margin-bottom: 10px; }
    .section-title { font-size: 1.8rem; font-weight: 700; letter-spacing: -0.02em; margin-bottom: 10px; }
    .section-sub { color: var(--muted); font-size: 0.95rem; line-height: 1.6; max-width: 560px; margin-bottom: 32px; }
    .pillars { display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; }
    .pillar { background: var(--surface); border: 1px solid var(--border); border-radius: 14px; padding: 24px; transition: all 0.2s; }
    .pillar:hover { border-color: var(--blue); transform: translateY(-2px); }
    .pillar-icon { width: 42px; height: 42px; border-radius: 10px; display: flex; align-items: center; justify-content: center; font-size: 20px; margin-bottom: 14px; }
    .pi-blue   { background: rgba(59,130,246,0.12); }
    .pi-green  { background: rgba(16,185,129,0.12); }
    .pi-purple { background: rgba(139,92,246,0.12); }
    .pi-amber  { background: rgba(245,158,11,0.12); }
    .pi-cyan   { background: rgba(34,211,238,0.12); }
    .pi-red    { background: rgba(239,68,68,0.12);  }
    .pillar h3 { font-size: 0.95rem; font-weight: 600; margin-bottom: 8px; }
    .pillar p  { font-size: 0.82rem; color: var(--muted); line-height: 1.6; }

    /* ── ATTACK CHIPS ── */
    .chip-row { display: flex; flex-wrap: wrap; gap: 8px; margin-top: 20px; }
    .chip { padding: 5px 12px; border-radius: 100px; font-size: 0.72rem; font-weight: 600; font-family: var(--mono); border: 1px solid; }
    .chip-red    { color: #f87171; border-color: rgba(239,68,68,0.3);   background: rgba(239,68,68,0.06); }
    .chip-amber  { color: #fbbf24; border-color: rgba(245,158,11,0.3); background: rgba(245,158,11,0.06); }
    .chip-purple { color: #a78bfa; border-color: rgba(139,92,246,0.3); background: rgba(139,92,246,0.06); }

    /* ── DIVIDER ── */
    .divider { border: none; border-top: 1px solid var(--border); max-width: 1200px; margin: 0 auto 60px; }

    /* ── WAR ROOM ── */
    .war-room { max-width: 1200px; margin: 0 auto; padding: 0 40px 60px; position: relative; z-index: 1; }
    .war-room-header { display: flex; align-items: center; justify-content: space-between; margin-bottom: 20px; }
    .war-room-title { display: flex; align-items: center; gap: 12px; }
    .war-room-title h2 { font-size: 1.3rem; font-weight: 700; }
    .gateway-badge { display: flex; align-items: center; gap: 6px; padding: 4px 12px; border-radius: 100px; background: rgba(16,185,129,0.1); border: 1px solid rgba(16,185,129,0.25); color: var(--green); font-size: 0.72rem; font-weight: 600; }

    .wr-grid { display: grid; grid-template-columns: 1fr 340px; gap: 16px; }
    .wr-left { display: flex; flex-direction: column; gap: 16px; }
    .wr-right { display: flex; flex-direction: column; gap: 16px; }

    .card { background: var(--surface); border: 1px solid var(--border); border-radius: 14px; overflow: hidden; }
    .card-hd { padding: 14px 18px; border-bottom: 1px solid var(--border); display: flex; align-items: center; justify-content: space-between; }
    .card-hd-title { font-size: 0.75rem; font-weight: 700; text-transform: uppercase; letter-spacing: 0.08em; color: var(--muted); }
    .card-body { padding: 18px; }

    /* controls */
    .ctrl-row { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin-bottom: 14px; }
    label.ctrl-label { font-size: 0.7rem; font-weight: 600; color: var(--muted); text-transform: uppercase; letter-spacing: 0.06em; display: block; margin-bottom: 6px; }
    select.ctrl-sel, input[type=range] { width: 100%; }
    select.ctrl-sel { background: var(--surface2); color: var(--text); border: 1px solid var(--border); border-radius: 8px; padding: 8px 10px; font-size: 0.82rem; outline: none; cursor: pointer; transition: border-color 0.2s; }
    select.ctrl-sel:hover, select.ctrl-sel:focus { border-color: var(--blue); }
    .risk-row { margin-bottom: 14px; }
    .risk-display { display: flex; justify-content: space-between; align-items: baseline; margin-bottom: 6px; }
    .risk-val { font-size: 1.4rem; font-weight: 800; font-family: var(--mono); color: var(--blue); }
    input[type=range] { -webkit-appearance: none; height: 6px; border-radius: 3px; background: var(--border); outline: none; margin: 0; }
    input[type=range]::-webkit-slider-thumb { -webkit-appearance: none; width: 18px; height: 18px; border-radius: 50%; background: var(--blue); cursor: pointer; box-shadow: 0 0 10px rgba(59,130,246,0.5); }
    .btn-row { display: flex; gap: 8px; flex-wrap: wrap; }
    .btn-sm { padding: 9px 16px; border-radius: 8px; font-size: 0.8rem; font-weight: 600; cursor: pointer; border: none; font-family: 'Inter', sans-serif; transition: all 0.18s; }
    .btn-run   { background: var(--blue);  color: #fff; flex: 1; }
    .btn-run:hover { opacity: 0.85; }
    .btn-reset { background: var(--surface2); color: var(--muted); border: 1px solid var(--border); }
    .btn-reset:hover { color: var(--text); border-color: var(--text); }
    .btn-clear { background: rgba(239,68,68,0.08); color: #f87171; border: 1px solid rgba(239,68,68,0.2); }

    /* status badges */
    .sb-row { display: flex; gap: 8px; flex-wrap: wrap; }
    .sb { display: inline-flex; align-items: center; gap: 5px; padding: 4px 10px; border-radius: 6px; font-size: 0.7rem; font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em; }
    .sb-green  { background: rgba(16,185,129,0.1);  color: var(--green);  border: 1px solid rgba(16,185,129,0.25); }
    .sb-red    { background: rgba(239,68,68,0.1);   color: #f87171;       border: 1px solid rgba(239,68,68,0.25); }
    .sb-amber  { background: rgba(245,158,11,0.1);  color: var(--amber);  border: 1px solid rgba(245,158,11,0.25); }
    .sb-blue   { background: rgba(59,130,246,0.1);  color: var(--blue);   border: 1px solid rgba(59,130,246,0.25); }
    .sb-purple { background: rgba(139,92,246,0.1);  color: #a78bfa;       border: 1px solid rgba(139,92,246,0.25); }
    .sb-dot    { width: 6px; height: 6px; border-radius: 50%; background: currentColor; }

    /* feed */
    .feed { font-family: var(--mono); font-size: 0.75rem; max-height: 240px; overflow-y: auto; background: #07111f; border-radius: 8px; padding: 12px; }
    .feed::-webkit-scrollbar { width: 4px; }
    .feed::-webkit-scrollbar-thumb { background: var(--border); border-radius: 2px; }
    .feed-line { padding: 4px 0; border-bottom: 1px solid rgba(30,45,69,0.5); line-height: 1.5; word-break: break-all; }
    .feed-line:last-child { border-bottom: none; }
    .f-ts  { color: var(--muted); margin-right: 8px; }
    .f-ok  { color: var(--green); }
    .f-bad { color: #f87171; }
    .f-warn{ color: var(--amber); }
    .f-info{ color: var(--blue); }
    .f-sys { color: var(--purple); }
    .feed-empty { color: var(--muted); font-style: italic; padding: 20px 0; text-align: center; }

    /* gauge */
    .gauge-wrap { display: flex; flex-direction: column; align-items: center; padding: 18px 0 8px; }
    .gauge-svg { transform: rotate(-90deg); }
    .gauge-track { fill: none; stroke: var(--border); stroke-width: 10; }
    .gauge-fill  { fill: none; stroke-width: 10; stroke-linecap: round; transition: stroke-dashoffset 0.6s cubic-bezier(.4,0,.2,1), stroke 0.4s; }
    .gauge-center { margin-top: -10px; text-align: center; }
    .gauge-pct  { font-size: 2rem; font-weight: 800; font-family: var(--mono); }
    .gauge-lbl  { font-size: 0.72rem; color: var(--muted); margin-top: 2px; text-transform: uppercase; letter-spacing: 0.08em; }

    /* reward */
    .reward-row { display: flex; justify-content: space-between; align-items: baseline; }
    .reward-val { font-size: 1.6rem; font-weight: 800; font-family: var(--mono); color: var(--cyan); }
    .reward-label { font-size: 0.72rem; color: var(--muted); }
    .mini-bars { display: flex; align-items: flex-end; gap: 3px; height: 36px; margin-top: 12px; }
    .mini-bar  { flex: 1; border-radius: 3px 3px 0 0; background: var(--blue); opacity: 0.6; transition: height 0.4s; min-height: 4px; }

    /* obs panel */
    .obs-pre { font-family: var(--mono); font-size: 0.7rem; color: var(--muted); white-space: pre-wrap; word-break: break-all; max-height: 160px; overflow-y: auto; }

    /* episode end toast */
    #episodeToast { position: fixed; bottom: 24px; right: 24px; background: var(--surface); border: 1px solid var(--green); border-radius: 12px; padding: 14px 20px; display: none; z-index: 999; box-shadow: 0 8px 30px rgba(0,0,0,0.5); font-size: 0.85rem; max-width: 300px; }
    #episodeToast.show { display: block; animation: slideUp 0.3s ease; }
    @keyframes slideUp { from{transform:translateY(20px);opacity:0} to{transform:translateY(0);opacity:1} }

    /* responsive */
    @media(max-width:900px){
      .wr-grid { grid-template-columns: 1fr; }
      .stats-row { grid-template-columns: repeat(2,1fr); }
      .pillars { grid-template-columns: 1fr; }
      .hero { padding: 60px 20px 40px; }
      .section, .war-room, .stats-row { padding-left: 20px; padding-right: 20px; }
    }
  </style>
</head>
<body>

  <!-- Background orbs -->
  <div class="orb orb-1"></div>
  <div class="orb orb-2"></div>
  <div class="orb orb-3"></div>

  <!-- Toast -->
  <div id="episodeToast">🏁 <strong>Episode Complete</strong><br><span id="toastMsg">New episode started.</span></div>

  <!-- NAV -->
  <nav>
    <div class="nav-logo">
      <div class="shield">🛡</div>
      GUARDIAN
      <span class="nav-pill">OpenEnv v0.2</span>
    </div>
    <div class="nav-links">
      <a href="#about" class="active">About</a>
      <a href="#war-room">Live Demo</a>
      <a href="/docs" target="_blank">API Docs</a>
    </div>
    <div style="font-size:0.78rem;color:var(--muted);display:flex;align-items:center">
      <span class="pulse-dot"></span> <span id="wsStatus">Connecting…</span>
    </div>
  </nav>

  <!-- ══ HERO ══ -->
  <div id="about">
  <section class="hero">
    <div class="hero-tag">🏆 Meta OpenEnv Hackathon — AI Security Track</div>
    <h1>AI agents will<br>act rogue.<br><span class="grad">We built the safety net.</span></h1>
    <p class="hero-sub">
      GUARDIAN is an LLM-based security overseer trained with GRPO to watch enterprise AI agents in real time — detecting 11 attack patterns from prompt injection to rogue AI, and intercepting them through an MCP gateway before production is compromised.
    </p>
    <div class="hero-cta">
      <button class="btn btn-primary" onclick="document.getElementById('war-room').scrollIntoView({behavior:'smooth'})">▶ Launch Live Demo</button>
      <a href="/docs" target="_blank"><button class="btn btn-ghost">View API Spec →</button></a>
    </div>
  </section>

  <!-- STATS -->
  <div class="stats-row">
    <div class="stat-card"><div class="stat-num stat-blue">11</div><div class="stat-label">Attack types covered</div></div>
    <div class="stat-card"><div class="stat-num stat-green">16</div><div class="stat-label">Reward signal components</div></div>
    <div class="stat-card"><div class="stat-num stat-amber">7B</div><div class="stat-label">Qwen2.5 Guardian model</div></div>
    <div class="stat-card"><div class="stat-num stat-purple">&lt;1s</div><div class="stat-label">Decision latency (T4 GPU)</div></div>
  </div>

  <!-- PILLARS -->
  <section class="section">
    <div class="section-label">Why GUARDIAN</div>
    <h2 class="section-title">The problem nobody solved yet.</h2>
    <p class="section-sub">Existing AI guardrails only add a static blocklist. GUARDIAN is a trained model that learns which actions are dangerous in context — and gets smarter every episode.</p>
    <div class="pillars">
      <div class="pillar">
        <div class="pillar-icon pi-red">⚡</div>
        <h3>Real-Time Interception</h3>
        <p>Every worker tool call is routed through an MCP-compliant gateway. Guardian decides in &lt;900ms: allow, shadow, quarantine, or emergency fork.</p>
      </div>
      <div class="pillar">
        <div class="pillar-icon pi-blue">🧠</div>
        <h3>Learns from Every Episode</h3>
        <p>GRPO training + self-distillation guarantees positive learning signal even on rare attack types. Guardian improves measurably across 120 training episodes.</p>
      </div>
      <div class="pillar">
        <div class="pillar-icon pi-purple">👤</div>
        <h3>Human in the Loop</h3>
        <p>Ambiguous grey-zone events (risk 0.45–0.75) escalate to a human decision via Telegram. The human's choice is replayed into the next GRPO training run.</p>
      </div>
      <div class="pillar">
        <div class="pillar-icon pi-green">🔗</div>
        <h3>MCP-Native Architecture</h3>
        <p>GUARDIAN acts as a standards-compliant MCP Security Gateway. It mediates all tool calls with semantic capability tags — enterprise-grade, not a demo hack.</p>
      </div>
      <div class="pillar">
        <div class="pillar-icon pi-amber">📊</div>
        <h3>16-Component Reward</h3>
        <p>Production safety, detection lag, reasoning quality, anti-gaming calibration. The reward is robust — the model can't exploit a single signal to farm points.</p>
      </div>
      <div class="pillar">
        <div class="pillar-icon pi-cyan">🕵️</div>
        <h3>Honeypot &amp; Taint Tracking</h3>
        <p>Suspected attacker traffic is silently routed to a honeypot environment. Multi-step taint propagation tracks financial exposure across all injected actions.</p>
      </div>
    </div>
    <div class="chip-row">
      <span class="chip chip-red">authority_spoofing</span>
      <span class="chip chip-red">prompt_injection</span>
      <span class="chip chip-red">rogue_internal_ai</span>
      <span class="chip chip-amber">approval_bypass</span>
      <span class="chip chip-amber">confused_deputy</span>
      <span class="chip chip-amber">delayed_exfiltration</span>
      <span class="chip chip-purple">salami_slicing</span>
      <span class="chip chip-purple">schema_drift_exploit</span>
      <span class="chip chip-purple">social_engineering</span>
      <span class="chip chip-amber">data_exfiltration</span>
      <span class="chip chip-amber">approval_laundering</span>
    </div>
  </section>
  </div>

  <hr class="divider">

  <!-- ══ WAR ROOM ══ -->
  <div id="war-room" class="war-room">
    <div class="war-room-header">
      <div class="war-room-title">
        <h2>⚔️ SOC War Room — Live Demo</h2>
        <span class="gateway-badge"><span class="pulse-dot"></span>MCP Gateway Active</span>
      </div>
      <div id="domainSel" style="display:flex;align-items:center;gap:10px">
        <label class="ctrl-label" style="margin:0">Domain</label>
        <select class="ctrl-sel" id="domainDropdown" style="width:auto" onchange="setDomain(this.value)">
          <option value="enterprise">🏢 Enterprise HR / Finance</option>
          <option value="finops">💳 FinOps (Trading)</option>
          <option value="healthcare">🏥 Healthcare</option>
        </select>
      </div>
    </div>

    <!-- Status bar -->
    <div class="sb-row" style="margin-bottom:16px" id="statusBar">
      <span class="sb sb-blue" id="sbStep"><span class="sb-dot"></span>STEP 0</span>
      <span class="sb sb-green" id="sbDb"><span class="sb-dot"></span>DB INTACT</span>
      <span class="sb sb-green" id="sbFork"><span class="sb-dot"></span>NO FORK</span>
      <span class="sb sb-green" id="sbProd"><span class="sb-dot"></span>SYSTEM CLEAN</span>
      <span class="sb sb-purple" id="sbReward"><span class="sb-dot"></span>REWARD: 0.000</span>
    </div>

    <div class="wr-grid">
      <!-- LEFT -->
      <div class="wr-left">

        <!-- Controls -->
        <div class="card">
          <div class="card-hd"><span class="card-hd-title">Guardian Decision Controls</span></div>
          <div class="card-body">
            <div class="ctrl-row">
              <div>
                <label class="ctrl-label">Intervention</label>
                <select class="ctrl-sel" id="ivSel">
                  <option value="allow">allow</option>
                  <option value="shadow">shadow (honeypot)</option>
                  <option value="rewrite">rewrite</option>
                  <option value="interrogate">interrogate</option>
                  <option value="reduce_privs">reduce_privs</option>
                  <option value="require_justification">require_justification</option>
                  <option value="quarantine_tool">quarantine_tool</option>
                  <option value="quarantine_agent">quarantine_agent 🚨</option>
                  <option value="rollback_k">rollback_k</option>
                  <option value="emergency_fork">emergency_fork 🔴</option>
                  <option value="canary_inject">canary_inject</option>
                  <option value="escalate_human">escalate_human</option>
                </select>
              </div>
              <div>
                <label class="ctrl-label">Classified Threat</label>
                <select class="ctrl-sel" id="attackSel">
                  <option value="">— None (clean) —</option>
                  <option value="authority_spoofing">authority_spoofing</option>
                  <option value="prompt_injection">prompt_injection</option>
                  <option value="approval_bypass">approval_bypass</option>
                  <option value="data_exfiltration">data_exfiltration</option>
                  <option value="confused_deputy">confused_deputy</option>
                  <option value="approval_laundering">approval_laundering</option>
                  <option value="salami_slicing">salami_slicing</option>
                  <option value="schema_drift_exploit">schema_drift_exploit</option>
                  <option value="rogue_internal_ai">rogue_internal_ai 🚨</option>
                  <option value="delayed_exfiltration">delayed_exfiltration</option>
                  <option value="social_engineering">social_engineering</option>
                </select>
              </div>
            </div>
            <div class="risk-row">
              <div class="risk-display">
                <label class="ctrl-label" style="margin:0">Assessed Risk Score</label>
                <span class="risk-val" id="riskDisplay">0.10</span>
              </div>
              <input type="range" id="riskSlider" min="0" max="100" value="10" oninput="document.getElementById('riskDisplay').textContent=(this.value/100).toFixed(2)">
            </div>
            <div class="btn-row">
              <button class="btn-sm btn-reset" onclick="doReset()">↺ Reset</button>
              <button class="btn-sm btn-run" onclick="doStep()">▶ Execute Step</button>
              <button class="btn-sm btn-clear" onclick="clearFeed()">✕ Clear</button>
            </div>
          </div>
        </div>

        <!-- MCP Feed -->
        <div class="card" style="flex:1">
          <div class="card-hd">
            <span class="card-hd-title">⚡ Telemetry &amp; MCP Intercept Feed</span>
            <span id="feedCount" style="font-size:0.72rem;color:var(--blue);font-weight:700;">0 EVENTS</span>
          </div>
          <div class="card-body" style="padding:12px">
            <div class="feed" id="feed"><div class="feed-empty">Awaiting enterprise telemetry hook…</div></div>
          </div>
        </div>

      </div>

      <!-- RIGHT -->
      <div class="wr-right">

        <!-- Risk Gauge -->
        <div class="card">
          <div class="card-hd"><span class="card-hd-title">🔴 Live Threat Assessment</span></div>
          <div class="card-body">
            <div class="gauge-wrap">
              <svg class="gauge-svg" width="140" height="140" viewBox="0 0 140 140">
                <circle class="gauge-track" cx="70" cy="70" r="54" />
                <circle class="gauge-fill" id="gaugeFill" cx="70" cy="70" r="54"
                  stroke="#3b82f6"
                  stroke-dasharray="339.3"
                  stroke-dashoffset="339.3" />
              </svg>
              <div class="gauge-center">
                <div class="gauge-pct" id="gaugePct" style="color:var(--blue)">0%</div>
                <div class="gauge-lbl" id="gaugeLbl">SYSTEM NORMAL</div>
              </div>
            </div>
          </div>
        </div>

        <!-- Cumulative Reward -->
        <div class="card">
          <div class="card-hd"><span class="card-hd-title">📈 Episode Reward</span></div>
          <div class="card-body">
            <div class="reward-row">
              <div><div class="reward-val" id="rewardVal">0.000</div><div class="reward-label">Cumulative reward</div></div>
              <div style="text-align:right"><div style="font-size:1.1rem;font-weight:700;color:var(--green)" id="episodeNum">#—</div><div class="reward-label">Episode</div></div>
            </div>
            <div class="mini-bars" id="miniBars"></div>
          </div>
        </div>

        <!-- Last Observation -->
        <div class="card" style="flex:1">
          <div class="card-hd"><span class="card-hd-title">🔵 Last Observation State</span></div>
          <div class="card-body">
            <pre class="obs-pre" id="obsPanel">{}</pre>
          </div>
        </div>

      </div>
    </div>
  </div>

  <script>
    const WS_URL = `${location.protocol === 'https:' ? 'wss' : 'ws'}://${location.host}/ws`;
    let ws, cumReward = 0, feedCount = 0, rewardHistory = [], stepNum = 0;
    const CIRCUMFERENCE = 339.3;

    // ── WebSocket ────────────────────────────────────────────────────────────
    function connect() {
      ws = new WebSocket(WS_URL);
      ws.onopen = () => { setWsStatus('Gateway Active', true); doReset(); };
      ws.onclose = () => { setWsStatus('Reconnecting…', false); setTimeout(connect, 3000); };
      ws.onerror = () => { setWsStatus('Connection Error', false); };
      ws.onmessage = e => handleMsg(JSON.parse(e.data));
    }

    function setWsStatus(txt, ok) {
      const el = document.getElementById('wsStatus');
      el.textContent = txt;
      el.style.color = ok ? 'var(--green)' : '#f87171';
    }

    function handleMsg(d) {
      if (d.type === 'reset_result' || d.type === 'episode_done') {
        if (d.type === 'episode_done') showToast('🏁 Episode done — auto-reset!', d.episode_id);
        cumReward = 0; stepNum = 0; rewardHistory = [];
        updateStatus(d.state || {}, 0);
        log('sys', `Episode reset — id: ${(d.state||{}).episode_id || '—'}`);
        updateObs(d.observation || {});
      }
      if (d.type === 'step_result') {
        stepNum++;
        const r = d.reward || 0;
        cumReward += r;
        rewardHistory.push(r);
        updateStatus(d.state || {}, cumReward);
        updateGauge(d.observation);
        updateObs(d.observation || {});
        updateBars();
        const iv = (d.state||{}).last_intervention || '—';
        const atk = (d.observation||{}).classified_attack || 'clean';
        const prod = (d.state||{}).production_intact !== false;
        const cls = r > 0.5 ? 'f-ok' : r > 0 ? 'f-warn' : 'f-bad';
        log(cls === 'f-ok' ? 'ok' : cls === 'f-warn' ? 'warn' : 'bad',
          `step=${stepNum} iv=${iv} threat=${atk} reward=${r.toFixed(4)} prod=${prod ? '✓' : '✗'}`);
      }
      if (d.type === 'error') log('bad', `Error: ${d.message}`);
    }

    // ── Actions ──────────────────────────────────────────────────────────────
    function doReset() {
      if (!ws || ws.readyState !== 1) return;
      ws.send(JSON.stringify({ type: 'reset' }));
    }
    function doStep() {
      if (!ws || ws.readyState !== 1) return;
      const action = {
        intervention:    document.getElementById('ivSel').value,
        attack_type:     document.getElementById('attackSel').value || null,
        risk_score:      parseFloat(document.getElementById('riskSlider').value) / 100,
        reasoning:       'Manual SOC decision via War Room UI',
      };
      ws.send(JSON.stringify({ type: 'step', action }));
    }
    function setDomain(d) {
      if (!ws || ws.readyState !== 1) return;
      ws.send(JSON.stringify({ type: 'set_domain', domain: d }));
      log('sys', `Domain switched → ${d}`);
    }
    function clearFeed() {
      document.getElementById('feed').innerHTML = '<div class="feed-empty">Feed cleared.</div>';
      feedCount = 0; document.getElementById('feedCount').textContent = '0 EVENTS';
    }

    // ── UI Helpers ────────────────────────────────────────────────────────────
    function ts() {
      const n = new Date();
      return `${String(n.getHours()).padStart(2,'0')}:${String(n.getMinutes()).padStart(2,'0')}:${String(n.getSeconds()).padStart(2,'0')}`;
    }
    function log(type, msg) {
      const feed = document.getElementById('feed');
      if (feed.querySelector('.feed-empty')) feed.innerHTML = '';
      feedCount++;
      document.getElementById('feedCount').textContent = feedCount + ' EVENTS';
      const cls = {ok:'f-ok',bad:'f-bad',warn:'f-warn',info:'f-info',sys:'f-sys'}[type] || 'f-info';
      const line = document.createElement('div');
      line.className = 'feed-line';
      line.innerHTML = `<span class="f-ts">${ts()}</span><span class="${cls}">${msg}</span>`;
      feed.appendChild(line);
      feed.scrollTop = feed.scrollHeight;
    }

    function updateStatus(state, reward) {
      const step   = state.step_count || stepNum || 0;
      const intact = state.production_intact !== false;
      const fork   = state.fork_triggered === true;
      const sys    = !fork && intact;
      const ep     = state.episode_id ? state.episode_id.slice(-8) : '—';

      document.getElementById('sbStep').innerHTML   = `<span class="sb-dot"></span>STEP ${step}`;
      document.getElementById('sbDb').className     = `sb ${intact ? 'sb-green' : 'sb-red'}`;
      document.getElementById('sbDb').innerHTML     = `<span class="sb-dot"></span>${intact ? 'DB INTACT' : 'DB BREACHED'}`;
      document.getElementById('sbFork').className   = `sb ${fork ? 'sb-red' : 'sb-green'}`;
      document.getElementById('sbFork').innerHTML   = `<span class="sb-dot"></span>${fork ? 'FORK TRIGGERED' : 'NO FORK'}`;
      document.getElementById('sbProd').className   = `sb ${sys ? 'sb-green' : 'sb-red'}`;
      document.getElementById('sbProd').innerHTML   = `<span class="sb-dot"></span>${sys ? 'SYSTEM CLEAN' : 'PRODUCTION AT RISK'}`;
      document.getElementById('sbReward').innerHTML = `<span class="sb-dot"></span>REWARD: ${reward.toFixed(3)}`;
      document.getElementById('rewardVal').textContent = reward.toFixed(4);
      document.getElementById('episodeNum').textContent = '#' + ep;
    }

    function updateGauge(obs) {
      if (!obs) return;
      const pct = Math.round((obs.risk_score || 0) * 100);
      const offset = CIRCUMFERENCE - (pct / 100) * CIRCUMFERENCE;
      const fill = document.getElementById('gaugeFill');
      const color = pct >= 75 ? '#ef4444' : pct >= 45 ? '#f59e0b' : '#3b82f6';
      fill.style.strokeDashoffset = offset;
      fill.style.stroke = color;
      const lbl = pct >= 75 ? 'HIGH RISK' : pct >= 45 ? 'ELEVATED' : 'SYSTEM NORMAL';
      document.getElementById('gaugePct').textContent = pct + '%';
      document.getElementById('gaugePct').style.color = color;
      document.getElementById('gaugeLbl').textContent = lbl;
    }

    function updateObs(obs) {
      if (!obs) return;
      const clean = {};
      ['current_step','production_intact','fork_triggered','classified_attack','risk_score','last_worker_tool','episode_id']
        .forEach(k => { if (obs[k] !== undefined) clean[k] = obs[k]; });
      document.getElementById('obsPanel').textContent = JSON.stringify(clean, null, 2);
    }

    function updateBars() {
      const bars = document.getElementById('miniBars');
      bars.innerHTML = '';
      const recent = rewardHistory.slice(-20);
      const max = Math.max(...recent, 0.01);
      recent.forEach(r => {
        const b = document.createElement('div');
        b.className = 'mini-bar';
        b.style.height = Math.max(4, Math.round((r / max) * 36)) + 'px';
        b.style.background = r > 0.5 ? 'var(--green)' : r > 0 ? 'var(--amber)' : '#ef4444';
        bars.appendChild(b);
      });
    }

    function showToast(title, ep) {
      const t = document.getElementById('episodeToast');
      document.getElementById('toastMsg').textContent = ep ? 'New episode: ' + ep.slice(-8) : 'Environment reset.';
      t.querySelector('strong').textContent = title;
      t.classList.add('show');
      setTimeout(() => t.classList.remove('show'), 4000);
    }

    // ── Startup ──────────────────────────────────────────────────────────────
    connect();
  </script>
</body>
</html>"""

# ── Entrypoint ────────────────────────────────────────────────────────────────

def main() -> None:
    """Called by `guardian-server` console script (pyproject.toml entry point)."""
    port = int(os.getenv("PORT", "8000"))
    host = os.getenv("HOST", "0.0.0.0")
    log.info(f"Starting uvicorn on {host}:{port}")
    uvicorn.run("server.app:app", host=host, port=port, reload=False)



if __name__ == "__main__":
    main()

