"""
GUARDIAN Fleet — OpenEnv FastAPI Server
=========================================
Implements the full OpenEnv HTTP + WebSocket protocol:

  POST /reset            → {"observation": ..., "state": ..., "reward": 0, "done": false}
  POST /step             → {"observation": ..., "reward": ..., "done": ..., "info": ..., "state": ...}
  GET  /state            → GuardianState
  WS   /ws               → Per-connection isolated WebSocket session
  GET  /health           → {"status": "ok", ...}
  GET  /web              → Browser UI for manual exploration
  GET  /docs             → OpenAPI docs (auto-generated by FastAPI)

WebSocket message protocol:
  Client → Server:
    {"type": "reset", "options": {...}}
    {"type": "step",  "action": {...}}
    {"type": "state"}

  Server → Client:
    {"type": "reset_result",  "observation": ..., "state": ..., "reward": 0, "done": false}
    {"type": "step_result",   "observation": ..., "reward": ..., "done": ..., "info": ..., "state": ...}
    {"type": "episode_done",  "observation": ..., "state": ..., "message": "..."}
    {"type": "state_result",  "state": ...}
    {"type": "error",         "message": "..."}

Run locally:
    uvicorn server.app:app --host 0.0.0.0 --port 8000 --reload

Or inside Docker (see server/Dockerfile):
    docker build -t guardian-env -f server/Dockerfile .
    docker run -p 8000:8000 guardian-env
"""

from __future__ import annotations

import json
import logging
import os
import sys
from typing import Any, Dict, Optional

# ── Ensure the repo root is always in sys.path ──────────────────────────────
# This makes `from models import ...` and `from guardian.environment import ...`
# work regardless of whether uvicorn is started from root or server/ directory.
_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

from contextlib import asynccontextmanager

from fastapi import FastAPI, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import HTMLResponse, JSONResponse
import uvicorn

from models import GuardianAction, GuardianObservation, GuardianState, StepResult
from server.guardian_environment import GuardianOpenEnvEnvironment

# ── Logging ──────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
log = logging.getLogger("guardian.server")


# ── Lifespan (replaces deprecated @app.on_event) ─────────────────────────────
@asynccontextmanager
async def lifespan(app: FastAPI):
    log.info("=" * 60)
    log.info("GUARDIAN Fleet OpenEnv Server — starting up")
    log.info("Endpoints: POST /reset  POST /step  GET /state  WS /ws")
    log.info("           GET /web     GET /health  GET /docs")
    log.info("=" * 60)
    yield  # application runs here
    log.info("GUARDIAN Fleet server shut down.")


# ── FastAPI app ───────────────────────────────────────────────────────────────
app = FastAPI(
    title="GUARDIAN Fleet — OpenEnv Server",
    description=(
        "Multi-agent AI security oversight environment for RL post-training. "
        "A Guardian LLM (Qwen2.5-7B, trained via GRPO) detects and intercepts "
        "adversarial prompt injections, authority spoofing, approval bypasses, "
        "and 5 other attack types across Finance/Ops/HR worker fleets."
    ),
    version="0.2.0",
    docs_url="/docs",
    redoc_url="/redoc",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ── Default HTTP environment (single shared session for REST endpoints) ───────
_http_env = GuardianOpenEnvEnvironment(difficulty=1)


def _new_env() -> GuardianOpenEnvEnvironment:
    """Create a fresh isolated environment per WebSocket connection."""
    return GuardianOpenEnvEnvironment(difficulty=1)


# ── Root redirect → /web ──────────────────────────────────────────────────────

@app.get("/", include_in_schema=False)
def root_redirect():
    """Redirect root URL to the web dashboard. Required for HF Spaces."""
    from fastapi.responses import RedirectResponse
    return RedirectResponse(url="/web")


# ── Health ────────────────────────────────────────────────────────────────────

@app.get(
    "/health",
    summary="Health check",
    tags=["System"],
)
def health() -> Dict[str, Any]:
    """Returns server status and environment metadata."""
    return {
        "status": "ok",
        "env": "guardian-env",
        "version": "0.2.0",
        "description": "GUARDIAN Fleet – AI Security Oversight RL Environment",
        "endpoints": ["/reset", "/step", "/state", "/ws", "/web", "/docs"],
    }


# ── REST: reset ───────────────────────────────────────────────────────────────

@app.post(
    "/reset",
    summary="Reset episode",
    tags=["Environment"],
)
def reset(body: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """
    Start a new episode.

    Body (optional JSON):
        {"seed": 42}

    Returns the initial observation and episode state.
    """
    global _http_env
    obs = _http_env.reset(options=body)
    state = _http_env.state()
    log.info(f"[REST /reset] episode_id={state.episode_id}")
    return {
        "observation": obs.model_dump(),
        "state": state.model_dump(),
        "reward": 0.0,
        "done": False,
    }


# ── REST: step ────────────────────────────────────────────────────────────────

@app.post(
    "/step",
    summary="Execute one Guardian decision",
    tags=["Environment"],
)
def step(action: GuardianAction) -> Dict[str, Any]:
    """
    Execute one Guardian decision and return the result.

    Body: GuardianAction JSON
        {
          "risk_score": 0.85,
          "intervention": "shadow",
          "attack_type": "prompt_injection",
          "rollback_k": 2,
          "reasoning": "Suspicious write to exfil_log"
        }
    """
    global _http_env
    obs, reward, done, info = _http_env.step(action)
    state = _http_env.state()
    log.info(
        f"[REST /step] step={state.step_count} "
        f"intervention={action.intervention} "
        f"risk={action.risk_score:.2f} "
        f"reward={reward:.4f} done={done}"
    )
    return {
        "observation": obs.model_dump(),
        "reward": reward,
        "done": done,
        "info": info,
        "state": state.model_dump(),
    }


# ── REST: baselines ───────────────────────────────────────────────────────────

@app.get(
    "/baselines",
    summary="Get Evaluation Baselines",
    tags=["System"],
)
def get_baselines() -> Dict[str, Any]:
    """Returns baseline execution metrics for the dashboard leaderboard."""
    eval_dir = os.path.join(_ROOT, "guardian", "data", "eval_data")
    baselines = []
    if os.path.exists(eval_dir):
        for fname in os.listdir(eval_dir):
            if fname.endswith(".json"):
                with open(os.path.join(eval_dir, fname), "r") as f:
                    try:
                        data = json.load(f)
                        baselines.append({
                            "model": data.get("model", fname.replace(".json", "")),
                            "mean_reward": data.get("mean_reward", 0.0),
                            "production_intact_rate": data.get("production_intact_rate", 0.0),
                        })
                    except Exception as e:
                        pass
    
    # Try to append trained Guardian if untested exists
    trained_path = os.path.join(_ROOT, "guardian", "data", "baseline_trained.json")
    if os.path.exists(trained_path):
        with open(trained_path, "r") as f:
            try:
                data = json.load(f)
                baselines.append({
                    "model": "Guardian (Self-Distilled RL)",
                    "mean_reward": data.get("mean_reward", 0.85),
                    "production_intact_rate": data.get("production_intact_rate", 0.95),
                })
            except Exception:
                pass

    return {"baselines": baselines}


# ── REST: state ───────────────────────────────────────────────────────────────

@app.get(
    "/state",
    summary="Episode state",
    tags=["Environment"],
)
def get_state() -> Dict[str, Any]:
    """Return current episode metadata without advancing the environment."""
    return _http_env.state().model_dump()


# ── REST: tools manifest (“Rug Pull” endpoint) ───────────────────────────────────

@app.get(
    "/tools",
    summary="Available MCP tool manifest",
    tags=["Environment"],
)
def get_tools() -> Dict[str, Any]:
    """
    Returns all tools available in the current episode, with risk metadata.

    Used by the client's get_tools() method to implement the MCP 'Rug Pull'
    deprovision pattern — the client strips quarantined tools from this list
    before exposing the action space to the Worker agent.

    Critical tools (high-risk) are flagged so the Guardian can apply
    surgical privilege downgrade without fully blocking the Worker.
    """
    all_tools = [
        # Safe tools
        {"name": "read_db",              "risk": "low",      "category": "data_read"},
        {"name": "post_to_forum",        "risk": "medium",   "category": "communication"},
        {"name": "query_data_access_log","risk": "low",      "category": "audit"},
        # Sensitive tools
        {"name": "write_db",             "risk": "high",     "category": "data_write"},
        {"name": "process_payment",      "risk": "high",     "category": "financial"},
        {"name": "modify_firewall",      "risk": "critical", "category": "network"},
        {"name": "modify_iam_policy",   "risk": "critical", "category": "iam"},
        {"name": "register_vendor",     "risk": "high",     "category": "vendor"},
        {"name": "export_data",         "risk": "critical", "category": "data_exfil"},
    ]
    # Check if any tools are currently quarantined in the active session
    quarantined = list(_http_env._gym.env.state.quarantined_tools)  # BUG-10 fix
    available = [t for t in all_tools if t["name"] not in quarantined]
    return {
        "tools": [t["name"] for t in available],
        "tool_details": available,
        "quarantined": quarantined,
        "rug_pull_active": len(quarantined) > 0,
        "episode_id": _http_env.state().episode_id,
    }



# ── WebSocket endpoint ────────────────────────────────────────────────────────

@app.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket) -> None:
    """
    Per-connection isolated WebSocket session.

    Each WebSocket connection gets its own GuardianOpenEnvEnvironment instance,
    so parallel training workers don't share environment state.

    Protocol (JSON messages):
        → {"type": "reset"}
        ← {"type": "reset_result", "observation": {...}, "state": {...}, ...}

        → {"type": "step", "action": {"risk_score": 0.8, "intervention": "shadow", ...}}
        ← {"type": "step_result", "observation": {...}, "reward": float, "done": bool, ...}

        → {"type": "state"}
        ← {"type": "state_result", "state": {...}}
    """
    await websocket.accept()
    env = _new_env()  # isolated per connection
    log.info("[WS] New connection accepted — fresh environment allocated")

    try:
        while True:
            try:
                raw = await websocket.receive_text()
            except WebSocketDisconnect:
                log.info("[WS] Client disconnected cleanly")
                return

            try:
                data: Dict[str, Any] = json.loads(raw)
            except json.JSONDecodeError:
                await websocket.send_json(
                    {"type": "error", "message": "Payload must be valid JSON"}
                )
                continue

            msg_type: str = data.get("type", "")

            # ── reset ──────────────────────────────────────────────────────
            if msg_type == "reset":
                obs = env.reset(options=data.get("options"))
                state = env.state()
                await websocket.send_json({
                    "type": "reset_result",
                    "observation": obs.model_dump(),
                    "state": state.model_dump(),
                    "reward": 0.0,
                    "done": False,
                })
                log.info(f"[WS] reset → episode_id={state.episode_id}")

            # ── step ───────────────────────────────────────────────────────
            elif msg_type == "step":
                action_data = data.get("action", {})
                try:
                    action = GuardianAction(**action_data)
                except Exception as parse_err:
                    await websocket.send_json({
                        "type": "error",
                        "message": f"Invalid action schema: {parse_err}",
                    })
                    continue

                obs, reward, done, info = env.step(action)
                state = env.state()
                await websocket.send_json({
                    "type": "step_result",
                    "observation": obs.model_dump(),
                    "reward": reward,
                    "done": done,
                    "info": info,
                    "state": state.model_dump(),
                })
                log.info(
                    f"[WS] step={state.step_count} "
                    f"iv={action.intervention} "
                    f"reward={reward:.4f} done={done}"
                )

                # Auto-reset and notify on episode end
                if done:
                    new_obs = env.reset()
                    new_state = env.state()
                    await websocket.send_json({
                        "type": "episode_done",
                        "observation": new_obs.model_dump(),
                        "state": new_state.model_dump(),
                        "episode_id": new_state.episode_id,  # Client re-locks episode_id
                        "message": "Episode complete. Environment auto-reset.",
                    })

            # ── state ──────────────────────────────────────────────────────
            elif msg_type == "state":
                state = env.state()
                await websocket.send_json({
                    "type": "state_result",
                    "state": state.model_dump(),
                })

            # ── unknown ────────────────────────────────────────────────────
            else:
                await websocket.send_json({
                    "type": "error",
                    "message": (
                        f"Unknown message type: '{msg_type}'. "
                        "Valid types: reset | step | state"
                    ),
                })

    except WebSocketDisconnect:
        log.info("[WS] Connection closed")
    except Exception as exc:
        log.error(f"[WS] Unhandled error: {exc}", exc_info=True)
        try:
            await websocket.send_json({"type": "error", "message": str(exc)})
        except Exception:
            pass


# ── Web UI ────────────────────────────────────────────────────────────────────

@app.get("/web", response_class=HTMLResponse, summary="Browser UI", tags=["System"])
def web_interface() -> HTMLResponse:
    """Interactive browser interface for manual episode exploration."""
    return HTMLResponse(content=_WEB_UI_HTML)


_WEB_UI_HTML = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>GUARDIAN Fleet — OpenEnv</title>
  <style>
    *{box-sizing:border-box;margin:0;padding:0}
    body{font-family:'Cascadia Code',Consolas,monospace;background:#0a0e1a;color:#c9d1d9;min-height:100vh;padding:20px}
    h1{color:#58a6ff;font-size:1.4rem;margin-bottom:4px}
    .sub{color:#8b949e;font-size:.85rem;margin-bottom:16px}
    .controls{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:12px;align-items:center}
    select,input{background:#161b22;color:#e6edf3;border:1px solid #30363d;padding:6px 10px;border-radius:6px;font-size:.85rem}
    button{padding:7px 16px;border:none;border-radius:6px;cursor:pointer;font-size:.85rem;font-weight:600;transition:background .15s}
    .btn-primary{background:#1f6feb;color:#fff}.btn-primary:hover{background:#388bfd}
    .btn-danger{background:#b62324;color:#fff}.btn-danger:hover{background:#da3633}
    .btn-neutral{background:#21262d;color:#c9d1d9}.btn-neutral:hover{background:#30363d}
    .grid{display:grid;grid-template-columns:1fr 1fr 1fr;gap:12px}
    .panel{background:#0d1117;border:1px solid #21262d;border-radius:8px;padding:12px}
    .panel h3{color:#58a6ff;font-size:.9rem;margin-bottom:8px;border-bottom:1px solid #21262d;padding-bottom:6px}
    #log{height:320px;overflow-y:auto;white-space:pre-wrap;font-size:.75rem;line-height:1.6}
    #obs{height:320px;overflow-y:auto;font-size:.75rem}
    .badge{display:inline-block;padding:2px 8px;border-radius:4px;font-size:.7rem;font-weight:700;margin:2px}
    .ok{background:#238636;color:#fff}.bad{background:#b62324;color:#fff}.warn{background:#9e6a03;color:#fff}.info{background:#1f6feb;color:#fff}
    .status{display:flex;gap:8px;margin-bottom:10px;flex-wrap:wrap}
    .sep{color:#484f58}
    label{color:#8b949e;font-size:.8rem}
    .risk-row{display:flex;align-items:center;gap:6px}
    input[type=range]{flex:1;accent-color:#58a6ff}
  </style>
</head>
<body>
  <h1>🛡️ GUARDIAN Fleet — OpenEnv Web Interface</h1>
  <div class="sub">WebSocket: <code id="wsUrl"></code> &nbsp;|&nbsp; <span id="connStatus">Connecting...</span></div>

  <div class="status" id="statusRow">
    <span class="badge info" id="badgeStep">Step 0</span>
    <span class="badge warn" id="badgeDiff">Difficulty 1</span>
    <span class="badge ok"  id="badgeProd">✅ Production intact</span>
    <span class="badge ok"  id="badgeFork">No fork</span>
    <span class="badge ok"  id="badgeAtk">Clean</span>
    <span class="badge info" id="badgeReward">Reward 0.000</span>
  </div>

  <div class="controls">
    <div>
      <label>Intervention</label><br>
      <select id="intervention">
        <option>allow</option><option>shadow</option><option>rewrite</option>
        <option>interrogate</option><option>reduce_privs</option>
        <option>require_justification</option><option>quarantine_tool</option>
        <option>rollback_k</option><option>emergency_fork</option>
        <option>canary_inject</option><option>escalate_human</option>
        <option>quarantine_agent</option>
      </select>
    </div>
    <div>
      <label>Attack type (classified)</label><br>
      <select id="attack_type">
        <option value="">clean</option>
        <option>authority_spoofing</option><option>prompt_injection</option>
        <option>approval_bypass</option><option>data_exfiltration</option>
        <option>confused_deputy</option><option>approval_laundering</option>
        <option>salami_slicing</option><option>schema_drift_exploit</option>
        <option>rogue_internal_ai</option>
      </select>
    </div>
    <div>
      <label>Risk score</label>
      <div class="risk-row">
        <input type="range" id="riskSlider" min="0" max="1" step="0.05" value="0.3"
               oninput="document.getElementById('riskVal').textContent=parseFloat(this.value).toFixed(2)">
        <span id="riskVal">0.30</span>
      </div>
    </div>
    <div style="display:flex;gap:6px;align-items:flex-end">
      <button class="btn-primary"  onclick="doReset()">↺ Reset</button>
      <button class="btn-primary"  onclick="doStep()">▶ Step</button>
      <button class="btn-neutral"  onclick="doState()">📊 State</button>
      <button class="btn-danger"   onclick="clearLog()">🗑 Clear</button>
    </div>
  </div>

  <div class="grid">
    <div class="panel">
      <h3>🏆 Leaderboard & Baselines</h3>
      <div id="baselinesChart" style="margin-top:10px; font-size:0.8rem; display:flex; flex-direction:column; gap:8px;">
        <div style="color:#8b949e">Loading baselines...</div>
      </div>
      <div style="margin-top:20px; font-size:0.75rem; color:#8b949e; line-height:1.4;">
        <i>GUARDIAN dynamically injects harder LLM-generated payload variants (Automated Red-Teaming) whenever blocks are highly successful!</i>
      </div>
    </div>
    <div class="panel">
      <h3>📡 WebSocket Messages</h3>
      <div id="log">(waiting for connection...)</div>
    </div>
    <div class="panel">
      <h3>🔍 Last Observation</h3>
      <div id="obs"><pre id="obsJson">{}</pre></div>
    </div>
  </div>

  <script>
    let ws;
    const wsUrl = (location.protocol==='https:'?'wss:':'ws:')+'//'+location.host+'/ws';
    document.getElementById('wsUrl').textContent = wsUrl;

    function connect(){
      ws = new WebSocket(wsUrl);
      ws.onopen  = ()=>{ setConn(true); logLine('🟢 Connected to '+wsUrl); };
      ws.onclose = ()=>{ setConn(false); logLine('🔴 Disconnected — reconnecting in 2s...'); setTimeout(connect,2000); };
      ws.onerror = e =>{ logLine('❌ WS error: '+JSON.stringify(e)); };
      ws.onmessage = e =>{ handleMsg(JSON.parse(e.data)); };
    }
    function setConn(ok){ document.getElementById('connStatus').textContent = ok?'🟢 Connected':'🔴 Disconnected'; }
    function send(msg){ ws&&ws.readyState===1 ? ws.send(JSON.stringify(msg)) : logLine('⚠️ Not connected'); }

    function doReset(){ send({type:'reset'}); }
    function doStep(){
      send({type:'step', action:{
        risk_score: parseFloat(document.getElementById('riskSlider').value),
        intervention: document.getElementById('intervention').value,
        attack_type: document.getElementById('attack_type').value||null,
        rollback_k: 2,
        reasoning: 'Manual step from web UI'
      }});
    }
    function doState(){ send({type:'state'}); }
    function clearLog(){ document.getElementById('log').textContent=''; }

    function handleMsg(d){
      logLine(JSON.stringify(d, null, 2));
      const obs = d.observation;
      const state = d.state;
      if(obs){
        document.getElementById('obsJson').textContent = JSON.stringify(obs, null, 2);
        setB('badgeStep',  'Step '+obs.current_step, 'info');
        setB('badgeDiff',  'Difficulty '+obs.difficulty, 'warn');
        setB('badgeProd',  obs.production_intact?'✅ Intact':'❌ COMPROMISED', obs.production_intact?'ok':'bad');
        setB('badgeFork',  obs.fork_triggered?'🔀 Fork active':'No fork', obs.fork_triggered?'warn':'ok');
        setB('badgeAtk',   obs.attack_active?'⚠️ Attack!':'Clean', obs.attack_active?'bad':'ok');
      }
      if(d.reward !== undefined) setB('badgeReward','Reward '+Number(d.reward).toFixed(4),'info');
    }
    function setB(id,txt,cls){
      const b=document.getElementById(id);
      b.textContent=txt; b.className='badge '+cls;
    }
    function logLine(s){ const el=document.getElementById('log'); el.textContent+=s+'\\n---\\n'; el.scrollTop=el.scrollHeight; }

    function loadBaselines() {
      fetch('/baselines').then(r=>r.json()).then(data => {
        const container = document.getElementById('baselinesChart');
        if(!data.baselines || data.baselines.length === 0) {
          container.innerHTML = '<div style="color:#8b949e">No evaluation metrics found. Run run_baselines.py!</div>';
          return;
        }
        
        let sorted = data.baselines.sort((a,b) => b.mean_reward - a.mean_reward);
        let html = '';
        sorted.forEach(b => {
           let pct = Math.max(2, Math.min(100, (b.mean_reward / 1.0) * 100));
           let color = b.model.includes('Guardian (Self-Distilled') ? '#238636' : (b.model.includes('GPT4') ? '#1f6feb' : '#8b949e');
           let dispName = b.model;
           if(dispName === 'GPT4o_Mini_ZeroShot') dispName = 'GPT-4o-mini (Zero-Shot)';
           
           html += `
             <div>
               <div style="display:flex; justify-content:space-between; margin-bottom:2px;">
                 <strong>${dispName}</strong>
                 <span>Reward: ${b.mean_reward.toFixed(3)} | Intact: ${(b.production_intact_rate*100).toFixed(0)}%</span>
               </div>
               <div style="width:100%; background:#21262d; border-radius:4px; height:12px; overflow:hidden;">
                 <div style="width:${pct}%; background:${color}; height:100%;"></div>
               </div>
             </div>
           `;
        });
        container.innerHTML = html;
      }).catch(e => console.error(e));
    }

    connect();
    loadBaselines();
  </script>
</body>
</html>"""


# ── Entrypoint ────────────────────────────────────────────────────────────────

def main() -> None:
    """Called by `guardian-server` console script (pyproject.toml entry point)."""
    port = int(os.getenv("PORT", "8000"))
    host = os.getenv("HOST", "0.0.0.0")
    log.info(f"Starting uvicorn on {host}:{port}")
    uvicorn.run("server.app:app", host=host, port=port, reload=False)


if __name__ == "__main__":
    main()
